-- ** Database generated with pgModeler (PostgreSQL Database Modeler).
-- ** pgModeler version: 1.2.3
-- ** PostgreSQL version: 18.0
-- ** Project Site: pgmodeler.io
-- ** Model Author: ---

-- ** Database creation must be performed outside a multi lined SQL file. 
-- ** These commands were put in this file only as a convenience.

SET search_path TO pg_catalog,public;
-- ddl-end --

-- object: public.person | type: TABLE --
-- DROP TABLE IF EXISTS public.person CASCADE;
CREATE TABLE public.person (
	per_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	per_name varchar(100) NOT NULL,
	per_identity_document integer NOT NULL,
	per_email varchar(100) NOT NULL,
	per_contact_number integer NOT NULL,
	per_state varchar(15) NOT NULL DEFAULT 'activo',
	per_update_date timestamptz,
	CONSTRAINT "Person_pk" PRIMARY KEY (per_id),
	CONSTRAINT "Person_idocument_uq" UNIQUE (per_identity_document),
	CONSTRAINT "Person_email_uq" UNIQUE (per_email),
	CONSTRAINT "Person_state_ck" CHECK (per_state IN ('activo','inactivo','bloqueado'))
);
-- ddl-end --
COMMENT ON TABLE public.person IS E'Representa a la persona corriente';
-- ddl-end --
COMMENT ON COLUMN public.person.per_id IS E'Index, identificador de persona (este valor puede asignarse, pero en caso contrario incrementa automaticamente)';
-- ddl-end --
COMMENT ON COLUMN public.person.per_name IS E'Nombre de la persona';
-- ddl-end --
COMMENT ON COLUMN public.person.per_identity_document IS E'Numero del documento de ciudadania';
-- ddl-end --
COMMENT ON COLUMN public.person.per_email IS E'Correo electronico de la persona';
-- ddl-end --
COMMENT ON COLUMN public.person.per_contact_number IS E'Numero de telefono mobil';
-- ddl-end --
COMMENT ON COLUMN public.person.per_state IS E'Estado actual de la cuenta';
-- ddl-end --
COMMENT ON COLUMN public.person.per_update_date IS E'Fecha y hora en la cual se concreto una actualizacion de los datos de una persona';
-- ddl-end --
COMMENT ON CONSTRAINT "Person_pk" ON public.person IS E'Restriccion de identificador unico para persona';
-- ddl-end --
COMMENT ON CONSTRAINT "Person_idocument_uq" ON public.person IS E'Restriccion que impidela repeticion de un documento de identidad';
-- ddl-end --
COMMENT ON CONSTRAINT "Person_email_uq" ON public.person IS E'Restriccion que impide la repeticion de un correo electronico';
-- ddl-end --
COMMENT ON CONSTRAINT "Person_state_ck" ON public.person IS E'Un estado solo puede ser activo, inactivo o bloqueado';
-- ddl-end --
ALTER TABLE public.person OWNER TO postgres;
-- ddl-end --

-- object: public.users | type: TABLE --
-- DROP TABLE IF EXISTS public.users CASCADE;
CREATE TABLE public.users (
	use_id integer NOT NULL,
	user_provider_id varchar(255) NOT NULL,
	user_provider_name varchar(25) NOT NULL,
	user_refresh_token varchar(255),
	CONSTRAINT "User_pk" PRIMARY KEY (use_id),
	CONSTRAINT "User_provider_uq" UNIQUE (user_provider_id,user_provider_name)
);
-- ddl-end --
COMMENT ON TABLE public.users IS E'Representa a la persona con cuenta dentro del sistema';
-- ddl-end --
COMMENT ON COLUMN public.users.use_id IS E'Index identificador del usuario (proviende de persona)';
-- ddl-end --
COMMENT ON COLUMN public.users.user_provider_id IS E'El identificador que fue dado/asignado por OAuth';
-- ddl-end --
COMMENT ON COLUMN public.users.user_provider_name IS E'El nombre del proovedor con el cual se hizo el inicio de sesion';
-- ddl-end --
COMMENT ON COLUMN public.users.user_refresh_token IS E'El hash bcrypt de nuestro JWT refresh token';
-- ddl-end --
COMMENT ON CONSTRAINT "User_pk" ON public.users IS E'Restriccion de identificador unico de usuario';
-- ddl-end --
COMMENT ON CONSTRAINT "User_provider_uq" ON public.users IS E'Restriccion que impide la repeticion de un id proovedor + nombre';
-- ddl-end --
ALTER TABLE public.users OWNER TO postgres;
-- ddl-end --

-- object: public.psychologist | type: TABLE --
-- DROP TABLE IF EXISTS public.psychologist CASCADE;
CREATE TABLE public.psychologist (
	psy_id integer NOT NULL,
	psy_license_number integer NOT NULL,
	psy_speciality varchar(45) NOT NULL,
	CONSTRAINT "Psychologist_pk" PRIMARY KEY (psy_id)
);
-- ddl-end --
COMMENT ON TABLE public.psychologist IS E'Representa al usuario el cual tiene como rol psicologo';
-- ddl-end --
COMMENT ON COLUMN public.psychologist.psy_id IS E'Index, identificador del psicologo, proviene de usuario';
-- ddl-end --
COMMENT ON COLUMN public.psychologist.psy_license_number IS E'El numero de licencia medico profesional para psicologos';
-- ddl-end --
COMMENT ON COLUMN public.psychologist.psy_speciality IS E'Especialidad profesional del psicologo';
-- ddl-end --
COMMENT ON CONSTRAINT "Psychologist_pk" ON public.psychologist IS E'Restriccion de identificador unico de psicologo';
-- ddl-end --
ALTER TABLE public.psychologist OWNER TO postgres;
-- ddl-end --

-- object: public.schedule | type: TABLE --
-- DROP TABLE IF EXISTS public.schedule CASCADE;
CREATE TABLE public.schedule (
	sch_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	psy_id integer NOT NULL,
	app_id integer,
	sch_date date NOT NULL,
	sch_start_time time NOT NULL,
	sch_end_time time NOT NULL,
	CONSTRAINT "Schedule_pk" PRIMARY KEY (sch_id),
	CONSTRAINT "Schedule_time_ck" CHECK (sch_end_time > sch_start_time)
);
-- ddl-end --
COMMENT ON TABLE public.schedule IS E'Representa las franjas horarias por la cual el psicologo esta ocupado';
-- ddl-end --
COMMENT ON COLUMN public.schedule.sch_id IS E'Index, identificador de la agenda o franja horaria (este valor puede asignarse, pero en caso contrario incrementa automaticamente)';
-- ddl-end --
COMMENT ON COLUMN public.schedule.psy_id IS E'Identificador del psicologo';
-- ddl-end --
COMMENT ON COLUMN public.schedule.app_id IS E'Identificador de la cita, en caso de que la razon de ocupacion sea por una';
-- ddl-end --
COMMENT ON COLUMN public.schedule.sch_date IS E'Fecha en la que el psicologo indica su indospinibilidad';
-- ddl-end --
COMMENT ON COLUMN public.schedule.sch_start_time IS E'Hora inicial en la que el psicologo indica su indospinibilidad';
-- ddl-end --
COMMENT ON COLUMN public.schedule.sch_end_time IS E'Hora final en la que el psicologo indica su indospinibilidad';
-- ddl-end --
COMMENT ON CONSTRAINT "Schedule_pk" ON public.schedule IS E'Restriccion de identificador unico de agenda';
-- ddl-end --
COMMENT ON CONSTRAINT "Schedule_time_ck" ON public.schedule IS E'Restriccion que obliga a que la hora de finalizacion sea posterior a la de inicio';
-- ddl-end --
ALTER TABLE public.schedule OWNER TO postgres;
-- ddl-end --

-- object: public.appointments | type: TABLE --
-- DROP TABLE IF EXISTS public.appointments CASCADE;
CREATE TABLE public.appointments (
	app_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	psy_id integer NOT NULL,
	sec_id integer NOT NULL,
	req_id integer NOT NULL,
	app_patient_person_id integer,
	app_patient_dependent_id integer,
	app_date timestamptz NOT NULL,
	app_state varchar(15) NOT NULL,
	app_type varchar(15) NOT NULL,
	CONSTRAINT "Appointments_pk" PRIMARY KEY (app_id),
	CONSTRAINT "Appointment_pacient_ck" CHECK ((app_patient_person_id IS NOT NULL) OR (app_patient_dependent_id IS NOT NULL)
)
);
-- ddl-end --
COMMENT ON TABLE public.appointments IS E'Representa la planeacion para el planteamiento de la cita psicologica';
-- ddl-end --
COMMENT ON COLUMN public.appointments.app_id IS E'Index, identificador de la cita (este valor puede asignarse, pero en caso contrario incrementa automaticamente)';
-- ddl-end --
COMMENT ON COLUMN public.appointments.psy_id IS E'Identificador del psicologo';
-- ddl-end --
COMMENT ON COLUMN public.appointments.sec_id IS E'Identificador del secretario';
-- ddl-end --
COMMENT ON COLUMN public.appointments.req_id IS E'Identificador del consultante';
-- ddl-end --
COMMENT ON COLUMN public.appointments.app_patient_person_id IS E'Identificador del paciente si este es para el propio consultante';
-- ddl-end --
COMMENT ON COLUMN public.appointments.app_patient_dependent_id IS E'Identificador del paciente si este es para un dependiente (menor de edad) registrado por el consultante';
-- ddl-end --
COMMENT ON COLUMN public.appointments.app_date IS E'Fecha de cuando inicia la cita';
-- ddl-end --
COMMENT ON COLUMN public.appointments.app_state IS E'Estado actual de la cita';
-- ddl-end --
COMMENT ON COLUMN public.appointments.app_type IS E'Tipo de la cita';
-- ddl-end --
COMMENT ON CONSTRAINT "Appointments_pk" ON public.appointments IS E'Restriccion de identificador unico de cita';
-- ddl-end --
COMMENT ON CONSTRAINT "Appointment_pacient_ck" ON public.appointments IS E'Restriccion que obliga que exista un paciente, sea el consultante o el dependiente';
-- ddl-end --
ALTER TABLE public.appointments OWNER TO postgres;
-- ddl-end --

-- object: public.rol | type: TABLE --
-- DROP TABLE IF EXISTS public.rol CASCADE;
CREATE TABLE public.rol (
	rol_id integer NOT NULL,
	rol_description varchar(25) NOT NULL,
	CONSTRAINT "Rol_pk" PRIMARY KEY (rol_id)
);
-- ddl-end --
COMMENT ON TABLE public.rol IS E'Clasificaccion de la persona la cual le brinda ciertos privilegios y responsabilidades';
-- ddl-end --
COMMENT ON COLUMN public.rol.rol_id IS E'Index, identificador de rol';
-- ddl-end --
COMMENT ON COLUMN public.rol.rol_description IS E'Descripcion o nombre del rol';
-- ddl-end --
COMMENT ON CONSTRAINT "Rol_pk" ON public.rol IS E'Restriccion de identificador unico de rol';
-- ddl-end --
ALTER TABLE public.rol OWNER TO postgres;
-- ddl-end --

-- object: public.person_rol | type: TABLE --
-- DROP TABLE IF EXISTS public.person_rol CASCADE;
CREATE TABLE public.person_rol (
	per_id integer NOT NULL,
	rol_id integer NOT NULL,
	pr_assigned_at timestamptz NOT NULL,
	CONSTRAINT "Person_Roles_pk" PRIMARY KEY (per_id,rol_id)
);
-- ddl-end --
COMMENT ON TABLE public.person_rol IS E'Tabla intermedia que vincula las personas con su/sus rol/roles';
-- ddl-end --
COMMENT ON COLUMN public.person_rol.per_id IS E'Identificador de la persona';
-- ddl-end --
COMMENT ON COLUMN public.person_rol.rol_id IS E'Identificador del rol';
-- ddl-end --
COMMENT ON COLUMN public.person_rol.pr_assigned_at IS E'Fecha y hora de la asignacion de un rol a una persona';
-- ddl-end --
COMMENT ON CONSTRAINT "Person_Roles_pk" ON public.person_rol IS E'Restriccion de identificacion unico compuesto con la id de la persona y rol';
-- ddl-end --
ALTER TABLE public.person_rol OWNER TO postgres;
-- ddl-end --

-- object: public.dependents | type: TABLE --
-- DROP TABLE IF EXISTS public.dependents CASCADE;
CREATE TABLE public.dependents (
	dep_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	dep_identity_document integer NOT NULL,
	dep_name varchar(100) NOT NULL,
	dep_contact_number integer NOT NULL,
	dep_birthdate date NOT NULL,
	CONSTRAINT "Dependents_pk" PRIMARY KEY (dep_id),
	CONSTRAINT "Dependent_idocument_uq" UNIQUE (dep_identity_document)
);
-- ddl-end --
COMMENT ON TABLE public.dependents IS E'Personas menores de edad, dependientes de su tutor legal. Se modelan en una tabla separada de Person (y no como subtipo) porque sus datos requieren tratamiento especial bajo la normativa de proteccion de datos de menores';
-- ddl-end --
COMMENT ON COLUMN public.dependents.dep_id IS E'Index, identificador de dependiente (menor de edad) (este valor puede asignarse, pero en caso contrario incrementa automaticamente)';
-- ddl-end --
COMMENT ON COLUMN public.dependents.dep_identity_document IS E'Numero del documento de ciudadania';
-- ddl-end --
COMMENT ON COLUMN public.dependents.dep_name IS E'Nombre del dependiente';
-- ddl-end --
COMMENT ON COLUMN public.dependents.dep_contact_number IS E'Numero de telefono mobil del dependiente';
-- ddl-end --
COMMENT ON COLUMN public.dependents.dep_birthdate IS E'Fecha de nacimiento del dependiente';
-- ddl-end --
COMMENT ON CONSTRAINT "Dependents_pk" ON public.dependents IS E'Restriccion de identificador unico de dependiente';
-- ddl-end --
COMMENT ON CONSTRAINT "Dependent_idocument_uq" ON public.dependents IS E'Restriccion que impide la repeticion de los documentos de identidad';
-- ddl-end --
ALTER TABLE public.dependents OWNER TO postgres;
-- ddl-end --

-- object: public.relationship | type: TABLE --
-- DROP TABLE IF EXISTS public.relationship CASCADE;
CREATE TABLE public.relationship (
	rel_id integer NOT NULL,
	rel_description varchar(25) NOT NULL,
	CONSTRAINT "Relationship_pk" PRIMARY KEY (rel_id)
);
-- ddl-end --
COMMENT ON TABLE public.relationship IS E'Tipos de relacion que tiene un menor de edad con su tutor legal';
-- ddl-end --
COMMENT ON COLUMN public.relationship.rel_id IS E'Index, identificador de relacion/parentesco';
-- ddl-end --
COMMENT ON COLUMN public.relationship.rel_description IS E'Descripcion o nombre del parentesco del consultante hacia el menor';
-- ddl-end --
COMMENT ON CONSTRAINT "Relationship_pk" ON public.relationship IS E'Identificador unico de la relacion';
-- ddl-end --
ALTER TABLE public.relationship OWNER TO postgres;
-- ddl-end --

-- object: public.donors | type: TABLE --
-- DROP TABLE IF EXISTS public.donors CASCADE;
CREATE TABLE public.donors (
	dono_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	dono_total_amount numeric(20,2),
	dono_email varchar(100) NOT NULL,
	dono_last_donation_date date,
	CONSTRAINT "Donors_pk" PRIMARY KEY (dono_id),
	CONSTRAINT "Donor_email_uq" UNIQUE (dono_email)
);
-- ddl-end --
COMMENT ON TABLE public.donors IS E'Representa a la persona corriente la cual desea realizar una donacion';
-- ddl-end --
COMMENT ON COLUMN public.donors.dono_id IS E'Index, identificador del donador (este valor puede asignarse, pero en caso contrario incrementa automaticamente)';
-- ddl-end --
COMMENT ON COLUMN public.donors.dono_total_amount IS E'Atributo calculado, suma las donaciones realizadas';
-- ddl-end --
COMMENT ON COLUMN public.donors.dono_email IS E'Correo del donante, subministrado por la API de la pasarela de pagos';
-- ddl-end --
COMMENT ON COLUMN public.donors.dono_last_donation_date IS E'Fecha de la ultima donacion realizada';
-- ddl-end --
COMMENT ON CONSTRAINT "Donors_pk" ON public.donors IS E'Restriccion de identificador unico de donador';
-- ddl-end --
COMMENT ON CONSTRAINT "Donor_email_uq" ON public.donors IS E'Restriccion que impide la repeticion del correo de los donantes';
-- ddl-end --
ALTER TABLE public.donors OWNER TO postgres;
-- ddl-end --

-- object: public.donations | type: TABLE --
-- DROP TABLE IF EXISTS public.donations CASCADE;
CREATE TABLE public.donations (
	dona_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	dono_id integer NOT NULL,
	pmet_id integer NOT NULL,
	dona_amount numeric(12,2) NOT NULL,
	dona_state varchar(10) NOT NULL,
	dona_description varchar(250),
	CONSTRAINT "Donations_pk" PRIMARY KEY (dona_id),
	CONSTRAINT "Donation_amount_ck" CHECK (dona_amount > 0)
);
-- ddl-end --
COMMENT ON TABLE public.donations IS E'Representa la donacion realizada por los donantes';
-- ddl-end --
COMMENT ON COLUMN public.donations.dona_id IS E'Index, identificador de la donacion (este valor puede asignarse, pero en caso contrario incrementa automaticamente)';
-- ddl-end --
COMMENT ON COLUMN public.donations.dono_id IS E'Identificador del donante';
-- ddl-end --
COMMENT ON COLUMN public.donations.pmet_id IS E'Identificador del metodo de pago';
-- ddl-end --
COMMENT ON COLUMN public.donations.dona_amount IS E'Cantidad donada';
-- ddl-end --
COMMENT ON COLUMN public.donations.dona_state IS E'Estado de la donacion dado por parte de la API';
-- ddl-end --
COMMENT ON COLUMN public.donations.dona_description IS E'Mensaje que puede ser dado por el donante';
-- ddl-end --
COMMENT ON CONSTRAINT "Donations_pk" ON public.donations IS E'Restriccion de identificador unico de las donaciones';
-- ddl-end --
COMMENT ON CONSTRAINT "Donation_amount_ck" ON public.donations IS E'Restriccion que obliga a que la cantidad donada sea superior a 0$';
-- ddl-end --
ALTER TABLE public.donations OWNER TO postgres;
-- ddl-end --

-- object: public.payment_method | type: TABLE --
-- DROP TABLE IF EXISTS public.payment_method CASCADE;
CREATE TABLE public.payment_method (
	pmet_id integer NOT NULL,
	pmet_is_active boolean NOT NULL DEFAULT true,
	pmet_name varchar(25) NOT NULL,
	CONSTRAINT "Payment_Method_pk" PRIMARY KEY (pmet_id)
);
-- ddl-end --
COMMENT ON TABLE public.payment_method IS E'Representa al metodo de pago con el cual se puede realizar una donacion';
-- ddl-end --
COMMENT ON COLUMN public.payment_method.pmet_id IS E'Index, identificador del metodo de pago';
-- ddl-end --
COMMENT ON COLUMN public.payment_method.pmet_is_active IS E'Estado en el cual se indica si un metodo de pago puede ser usado';
-- ddl-end --
COMMENT ON COLUMN public.payment_method.pmet_name IS E'Nombre del servicio usado';
-- ddl-end --
COMMENT ON CONSTRAINT "Payment_Method_pk" ON public.payment_method IS E'Restriccion de identificador unico del metodo de pago';
-- ddl-end --
ALTER TABLE public.payment_method OWNER TO postgres;
-- ddl-end --

-- object: public.requester_dependent | type: TABLE --
-- DROP TABLE IF EXISTS public.requester_dependent CASCADE;
CREATE TABLE public.requester_dependent (
	req_id integer NOT NULL,
	dep_id integer NOT NULL,
	rel_id integer,
	rd_assigned_at timestamptz NOT NULL,
	CONSTRAINT "Requester_Dependent_pk" PRIMARY KEY (req_id,dep_id)
);
-- ddl-end --
COMMENT ON TABLE public.requester_dependent IS E'Tabla intermedia, vincula los consultantes con los menores de edad segun su parentesco';
-- ddl-end --
COMMENT ON COLUMN public.requester_dependent.req_id IS E'Identificador del consultante';
-- ddl-end --
COMMENT ON COLUMN public.requester_dependent.dep_id IS E'Identificador del dependiente (menor de edad)';
-- ddl-end --
COMMENT ON COLUMN public.requester_dependent.rel_id IS E'Identificador de la relacion (parentesco)';
-- ddl-end --
COMMENT ON COLUMN public.requester_dependent.rd_assigned_at IS E'Fecha y hora en la que un consultante registro a un menor de idad y definio su parentesco con este';
-- ddl-end --
COMMENT ON CONSTRAINT "Requester_Dependent_pk" ON public.requester_dependent IS E'Restriccion Identificador unico que junta el id de un consultante y un dependiente';
-- ddl-end --
ALTER TABLE public.requester_dependent OWNER TO postgres;
-- ddl-end --

-- object: "User_Person_fk" | type: CONSTRAINT --
-- ALTER TABLE public.users DROP CONSTRAINT IF EXISTS "User_Person_fk" CASCADE;
ALTER TABLE public.users ADD CONSTRAINT "User_Person_fk" FOREIGN KEY (use_id)
REFERENCES public.person (per_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "User_Person_fk" ON public.users IS E'Identificador proveniente de persona';
-- ddl-end --


-- object: "Psychologist_User_fk" | type: CONSTRAINT --
-- ALTER TABLE public.psychologist DROP CONSTRAINT IF EXISTS "Psychologist_User_fk" CASCADE;
ALTER TABLE public.psychologist ADD CONSTRAINT "Psychologist_User_fk" FOREIGN KEY (psy_id)
REFERENCES public.users (use_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Psychologist_User_fk" ON public.psychologist IS E'Identificador proveniente de usuario';
-- ddl-end --


-- object: "Schedule_Psychologist_fk" | type: CONSTRAINT --
-- ALTER TABLE public.schedule DROP CONSTRAINT IF EXISTS "Schedule_Psychologist_fk" CASCADE;
ALTER TABLE public.schedule ADD CONSTRAINT "Schedule_Psychologist_fk" FOREIGN KEY (psy_id)
REFERENCES public.psychologist (psy_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Schedule_Psychologist_fk" ON public.schedule IS E'Identificador proveniente de psicologo';
-- ddl-end --


-- object: "Schedule_Appointment_fk" | type: CONSTRAINT --
-- ALTER TABLE public.schedule DROP CONSTRAINT IF EXISTS "Schedule_Appointment_fk" CASCADE;
ALTER TABLE public.schedule ADD CONSTRAINT "Schedule_Appointment_fk" FOREIGN KEY (app_id)
REFERENCES public.appointments (app_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Schedule_Appointment_fk" ON public.schedule IS E'Identificador proveniente de cita';
-- ddl-end --


-- object: "Appointment_Psychologist_fk" | type: CONSTRAINT --
-- ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS "Appointment_Psychologist_fk" CASCADE;
ALTER TABLE public.appointments ADD CONSTRAINT "Appointment_Psychologist_fk" FOREIGN KEY (psy_id)
REFERENCES public.psychologist (psy_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Appointment_Psychologist_fk" ON public.appointments IS E'Identificador proveniente del psicologo';
-- ddl-end --


-- object: "Appointment_Secretary_fk" | type: CONSTRAINT --
-- ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS "Appointment_Secretary_fk" CASCADE;
ALTER TABLE public.appointments ADD CONSTRAINT "Appointment_Secretary_fk" FOREIGN KEY (sec_id)
REFERENCES public.users (use_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Appointment_Secretary_fk" ON public.appointments IS E'Identificador proveniente de usuario (secretario)';
-- ddl-end --


-- object: "Appointment_Requester_fk" | type: CONSTRAINT --
-- ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS "Appointment_Requester_fk" CASCADE;
ALTER TABLE public.appointments ADD CONSTRAINT "Appointment_Requester_fk" FOREIGN KEY (req_id)
REFERENCES public.person (per_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Appointment_Requester_fk" ON public.appointments IS E'Identificador proveniente de persona (consultante)';
-- ddl-end --


-- object: "Appointment_Pacient_fk" | type: CONSTRAINT --
-- ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS "Appointment_Pacient_fk" CASCADE;
ALTER TABLE public.appointments ADD CONSTRAINT "Appointment_Pacient_fk" FOREIGN KEY (app_patient_person_id)
REFERENCES public.person (per_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Appointment_Pacient_fk" ON public.appointments IS E'Identificador proveniente de persona (consultante), implica que la cita es para el mismo consultante';
-- ddl-end --


-- object: "Appointment_Dependent_fk" | type: CONSTRAINT --
-- ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS "Appointment_Dependent_fk" CASCADE;
ALTER TABLE public.appointments ADD CONSTRAINT "Appointment_Dependent_fk" FOREIGN KEY (app_patient_dependent_id)
REFERENCES public.dependents (dep_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Appointment_Dependent_fk" ON public.appointments IS E'Identificador proveniente de dependiente, implica que la cita solicitada por el consultante es para este menor de edad';
-- ddl-end --


-- object: "PR_Person_fk" | type: CONSTRAINT --
-- ALTER TABLE public.person_rol DROP CONSTRAINT IF EXISTS "PR_Person_fk" CASCADE;
ALTER TABLE public.person_rol ADD CONSTRAINT "PR_Person_fk" FOREIGN KEY (per_id)
REFERENCES public.person (per_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "PR_Person_fk" ON public.person_rol IS E'Identificador proveniente de persona';
-- ddl-end --


-- object: "PR_Rol_fk" | type: CONSTRAINT --
-- ALTER TABLE public.person_rol DROP CONSTRAINT IF EXISTS "PR_Rol_fk" CASCADE;
ALTER TABLE public.person_rol ADD CONSTRAINT "PR_Rol_fk" FOREIGN KEY (rol_id)
REFERENCES public.rol (rol_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "PR_Rol_fk" ON public.person_rol IS E'Identificador proveniente de rol';
-- ddl-end --


-- object: "Donation_Donor_fk" | type: CONSTRAINT --
-- ALTER TABLE public.donations DROP CONSTRAINT IF EXISTS "Donation_Donor_fk" CASCADE;
ALTER TABLE public.donations ADD CONSTRAINT "Donation_Donor_fk" FOREIGN KEY (dono_id)
REFERENCES public.donors (dono_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Donation_Donor_fk" ON public.donations IS E'Identificador proveniente del donante';
-- ddl-end --


-- object: "Donation_PMethod_fk" | type: CONSTRAINT --
-- ALTER TABLE public.donations DROP CONSTRAINT IF EXISTS "Donation_PMethod_fk" CASCADE;
ALTER TABLE public.donations ADD CONSTRAINT "Donation_PMethod_fk" FOREIGN KEY (pmet_id)
REFERENCES public.payment_method (pmet_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Donation_PMethod_fk" ON public.donations IS E'Identificador que proviene del metodo de pago';
-- ddl-end --


-- object: "RD_Requester_fk" | type: CONSTRAINT --
-- ALTER TABLE public.requester_dependent DROP CONSTRAINT IF EXISTS "RD_Requester_fk" CASCADE;
ALTER TABLE public.requester_dependent ADD CONSTRAINT "RD_Requester_fk" FOREIGN KEY (req_id)
REFERENCES public.person (per_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "RD_Requester_fk" ON public.requester_dependent IS E'Identificador proveniente de persona (consultante)';
-- ddl-end --


-- object: "RD_Dependent_fk" | type: CONSTRAINT --
-- ALTER TABLE public.requester_dependent DROP CONSTRAINT IF EXISTS "RD_Dependent_fk" CASCADE;
ALTER TABLE public.requester_dependent ADD CONSTRAINT "RD_Dependent_fk" FOREIGN KEY (dep_id)
REFERENCES public.dependents (dep_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "RD_Dependent_fk" ON public.requester_dependent IS E'Identificador proveniente de dependiente';
-- ddl-end --


-- object: "RD_Relationship_fk" | type: CONSTRAINT --
-- ALTER TABLE public.requester_dependent DROP CONSTRAINT IF EXISTS "RD_Relationship_fk" CASCADE;
ALTER TABLE public.requester_dependent ADD CONSTRAINT "RD_Relationship_fk" FOREIGN KEY (rel_id)
REFERENCES public.relationship (rel_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "RD_Relationship_fk" ON public.requester_dependent IS E'Identificador proveniente de relacion (parentesco)';
-- ddl-end --

------------------------- MIGRATION 11/09/2026 -------------------------

ALTER TABLE public.person
    ALTER COLUMN per_identity_document DROP NOT NULL,
    ALTER COLUMN per_contact_number DROP NOT NULL;

ALTER TABLE public.person
    DROP CONSTRAINT IF EXISTS "Person_state_ck";

ALTER TABLE public.person
    ADD CONSTRAINT "Person_state_ck"
    CHECK (per_state IN ('activo', 'inactivo', 'bloqueado', 'pendiente'));

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS user_last_login_at timestamptz;

CREATE TABLE IF NOT EXISTS public.access_requests (
    access_request_id integer GENERATED BY DEFAULT AS IDENTITY,
    per_id integer NOT NULL,
    access_request_status varchar(15) NOT NULL DEFAULT 'pending',
    access_request_created_at timestamptz NOT NULL DEFAULT now(),
    access_request_updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Access_Request_pk" PRIMARY KEY (access_request_id),
    CONSTRAINT "Access_Request_person_uq" UNIQUE (per_id),
    CONSTRAINT "Access_Request_status_ck"
        CHECK (access_request_status IN ('pending', 'approved', 'rejected')),
    CONSTRAINT "Access_Request_person_fk"
        FOREIGN KEY (per_id) REFERENCES public.person (per_id)
);

CREATE TABLE IF NOT EXISTS public.auth_sessions (
    auth_session_id uuid PRIMARY KEY,
    use_id integer NOT NULL,
    auth_session_refresh_token_hash varchar(255) NOT NULL,
    auth_session_last_activity_at timestamptz NOT NULL DEFAULT now(),
    auth_session_expires_at timestamptz NOT NULL,
    auth_session_revoked_at timestamptz,
    auth_session_created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Auth_Session_user_fk"
        FOREIGN KEY (use_id) REFERENCES public.users (use_id)
);

CREATE INDEX IF NOT EXISTS "Person_email_idx"
    ON public.person (lower(per_email));

CREATE INDEX IF NOT EXISTS "Auth_Session_user_idx"
    ON public.auth_sessions (use_id);

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS user_refresh_token varchar(255);

COMMENT ON COLUMN public.users.user_refresh_token
    IS E'El hash bcrypt de nuestro JWT refresh token';

------------------------- MIGRATION 14/09/2026 -------------------------
-- HU-1.3: un usuario puede tener varios roles a la vez, cada uno activable
-- o desactivable por separado sin perder la asignacion (lo que ya construyo
-- el frontend en feat/auth-states). person_rol solo tenia per_id+rol_id.
ALTER TABLE public.person_rol
    ADD COLUMN IF NOT EXISTS pr_active boolean NOT NULL DEFAULT true;

COMMENT ON COLUMN public.person_rol.pr_active
    IS E'Indica si el rol asignado esta activo (se puede desactivar sin quitarlo)';

-- per_contact_number en integer se desborda con cualquier celular colombiano
-- real (3xxxxxxxxx > 2147483647, el maximo de int4). Se amplia a bigint;
-- es un ensanchamiento seguro, no hay perdida de datos.
ALTER TABLE public.person
    ALTER COLUMN per_contact_number TYPE bigint;
---- Modifications 14/09/2026 ----

COMMENT ON COLUMN public.users.user_last_login_at
    IS E'Fecha y hora del ultimo inicio de sesion exitoso del usuario a traves de OAuth';

CREATE TABLE IF NOT EXISTS public.security_access_log (
    security_access_log_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    use_id integer NOT NULL,
    auth_session_id uuid,
    security_access_log_section varchar(100) NOT NULL,
    security_access_log_message varchar(255) NOT NULL,
    security_access_log_created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Security_Access_Log_pk" PRIMARY KEY (security_access_log_id),
    CONSTRAINT "Security_Access_Log_User_fk" FOREIGN KEY (use_id)
        REFERENCES public.users (use_id) MATCH SIMPLE
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Security_Access_Log_Session_fk" FOREIGN KEY (auth_session_id)
        REFERENCES public.auth_sessions (auth_session_id) MATCH SIMPLE
        ON DELETE SET NULL ON UPDATE NO ACTION
);
 
COMMENT ON TABLE public.security_access_log
    IS E'Registro de seguridad: avisos generados por el sistema cuando un usuario intenta acceder a una seccion para la cual no tiene permisos';
COMMENT ON COLUMN public.security_access_log.security_access_log_id
    IS E'Index, identificador del registro de seguridad (incrementa automaticamente)';
COMMENT ON COLUMN public.security_access_log.use_id
    IS E'Identificador del usuario que intento acceder a la seccion no autorizada';
COMMENT ON COLUMN public.security_access_log.auth_session_id
    IS E'Identificador de la sesion activa desde la cual se genero el intento (opcional)';
COMMENT ON COLUMN public.security_access_log.security_access_log_section
    IS E'Seccion, ruta o recurso al cual el usuario intento acceder sin autorizacion';
COMMENT ON COLUMN public.security_access_log.security_access_log_message
    IS E'Mensaje o aviso generado por el sistema al detectar el intento de acceso no autorizado';
COMMENT ON COLUMN public.security_access_log.security_access_log_created_at
    IS E'Fecha y hora en la que se genero el aviso de seguridad';
 
COMMENT ON CONSTRAINT "Security_Access_Log_pk" ON public.security_access_log
    IS E'Restriccion de identificador unico del registro de seguridad';
COMMENT ON CONSTRAINT "Security_Access_Log_User_fk" ON public.security_access_log
    IS E'Identificador proveniente de usuario, indica quien intento el acceso no autorizado';
COMMENT ON CONSTRAINT "Security_Access_Log_Session_fk" ON public.security_access_log
    IS E'Identificador proveniente de la sesion de autenticacion activa durante el intento';
 
CREATE INDEX IF NOT EXISTS "Security_Access_Log_user_idx"
    ON public.security_access_log (use_id);
 
CREATE INDEX IF NOT EXISTS "Security_Access_Log_created_idx"
    ON public.security_access_log (security_access_log_created_at);

ALTER TABLE public.donations
    DROP CONSTRAINT IF EXISTS "Donation_state_ck";
 
ALTER TABLE public.donations
    ADD CONSTRAINT "Donation_state_ck"
    CHECK (dona_state IN ('PENDING', 'APPROVED', 'DECLINED', 'VOIDED', 'ERROR'));
 
COMMENT ON CONSTRAINT "Donation_state_ck" ON public.donations
    IS E'Restringe dona_state a los estados posibles de una transaccion de Wompi';
 
CREATE OR REPLACE FUNCTION public.fn_update_donor_total_amount()
RETURNS trigger AS $$
DECLARE
    v_dono_id integer;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_dono_id := OLD.dono_id;
    ELSE
        v_dono_id := NEW.dono_id;
    END IF;
 
    UPDATE public.donors
       SET dono_total_amount = (
                SELECT COALESCE(SUM(dona_amount), 0)
                  FROM public.donations
                 WHERE dono_id = v_dono_id
                   AND dona_state = 'APPROVED'
           )
     WHERE dono_id = v_dono_id;
 
    IF TG_OP = 'UPDATE' AND OLD.dono_id IS DISTINCT FROM NEW.dono_id THEN
        UPDATE public.donors
           SET dono_total_amount = (
                    SELECT COALESCE(SUM(dona_amount), 0)
                      FROM public.donations
                     WHERE dono_id = OLD.dono_id
                       AND dona_state = 'APPROVED'
               )
         WHERE dono_id = OLD.dono_id;
    END IF;
 
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
 
DROP TRIGGER IF EXISTS trg_donations_update_donor_total ON public.donations;
 
CREATE TRIGGER trg_donations_update_donor_total
AFTER INSERT OR UPDATE OF dona_amount, dona_state, dono_id OR DELETE
ON public.donations
FOR EACH ROW
EXECUTE FUNCTION public.fn_update_donor_total_amount();
 
COMMENT ON FUNCTION public.fn_update_donor_total_amount()
    IS E'Recalcula donors.dono_total_amount como la suma de las donaciones completadas del donante, tras cada insercion, actualizacion o borrado en donations';

---- Testing ----

ALTER TABLE public.auth_sessions
    ALTER COLUMN auth_session_id SET DEFAULT gen_random_uuid();
 
ALTER TABLE public.auth_sessions
    ADD COLUMN IF NOT EXISTS auth_session_previous_token_hash varchar(255);
 
ALTER TABLE public.auth_sessions
    ADD COLUMN IF NOT EXISTS auth_session_revoked_reason varchar(20);
 
ALTER TABLE public.auth_sessions
    DROP CONSTRAINT IF EXISTS "Auth_Session_revoked_reason_ck";
 
ALTER TABLE public.auth_sessions
    ADD CONSTRAINT "Auth_Session_revoked_reason_ck"
    CHECK (auth_session_revoked_reason IS NULL OR auth_session_revoked_reason IN
        ('logout', 'rotated', 'reuse_detected', 'expired', 'admin'));
 
COMMENT ON COLUMN public.auth_sessions.auth_session_previous_token_hash
    IS E'Hash del refresh token inmediatamente anterior al actual (el que se reemplazo en la ultima rotacion). Si un token entrante coincide con este valor, es un intento de reuso y la sesion debe revocarse de inmediato';
COMMENT ON COLUMN public.auth_sessions.auth_session_revoked_reason
    IS E'Motivo de revocacion: logout, rotated (reemplazada por rotacion normal, no implica riesgo), reuse_detected (posible robo de token, requiere forzar re-login), expired o admin';
COMMENT ON CONSTRAINT "Auth_Session_revoked_reason_ck" ON public.auth_sessions
    IS E'Restringe el motivo de revocacion a valores conocidos';

----

ALTER TABLE public.users
    DROP COLUMN IF EXISTS user_refresh_token;

CREATE OR REPLACE FUNCTION public.fn_cleanup_expired_sessions(p_retention_days integer DEFAULT 30)
RETURNS integer AS $$
DECLARE
    v_deleted_count integer;
BEGIN
    DELETE FROM public.auth_sessions
     WHERE (auth_session_revoked_at IS NOT NULL AND auth_session_revoked_at < now() - (p_retention_days || ' days')::interval)
        OR (auth_session_expires_at < now() - (p_retention_days || ' days')::interval);

    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RETURN v_deleted_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.fn_cleanup_expired_sessions(integer)
    IS E'Purga sesiones de autenticacion revocadas o expiradas que superan el periodo de retencion en dias (por defecto 30 dias)';

CREATE OR REPLACE FUNCTION public.fn_cleanup_old_security_logs(p_retention_days integer DEFAULT 180)
RETURNS integer AS $$
DECLARE
    v_deleted_count integer;
BEGIN
    DELETE FROM public.security_access_log
     WHERE security_access_log_created_at < now() - (p_retention_days || ' days')::interval;

    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RETURN v_deleted_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.fn_cleanup_old_security_logs(integer)
    IS E'Purga registros de auditoria de seguridad que superan el periodo de retencion en dias (por defecto 180 dias) para cumplir con minimizacion de datos';


------------------------- MIGRATION: 15/09/2026 -------------------------

DO $$
DECLARE
  fk_name text;
BEGIN
  SELECT conname INTO fk_name
  FROM pg_constraint
  WHERE conrelid = 'public.security_access_log'::regclass
    AND confrelid = 'public.auth_sessions'::regclass
    AND contype = 'f';

  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.security_access_log DROP CONSTRAINT %I', fk_name);
  END IF;
END $$;

ALTER TABLE public.security_access_log
    DROP COLUMN IF EXISTS auth_session_id;

DROP FUNCTION IF EXISTS public.fn_cleanup_expired_sessions;

DROP TABLE IF EXISTS public.auth_sessions;

------------------------- MIGRATION: fixes person/users -------------------------

ALTER TABLE public.person
    DROP CONSTRAINT IF EXISTS "Person_email_uq";

DROP INDEX IF EXISTS "Person_email_idx";

CREATE UNIQUE INDEX "Person_email_uq" ON public.person (lower(per_email));

COMMENT ON INDEX public."Person_email_uq"
    IS E'Unicidad y busqueda case-insensitive del correo; evita duplicar persona por diferencias de mayusculas entre proveedores OAuth';
ALTER TABLE public.users
    DROP CONSTRAINT IF EXISTS "User_provider_uq";

ALTER TABLE public.users
    ADD CONSTRAINT "User_provider_uq" UNIQUE (user_provider_id);

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS user_email_verified boolean NOT NULL DEFAULT false;
