-- ** Database generated with pgModeler (PostgreSQL Database Modeler).
-- ** pgModeler version: 1.2.3
-- ** PostgreSQL version: 18.0
-- ** Project Site: pgmodeler.io
-- ** Model Author: ---

-- ** Database creation must be performed outside a multi lined SQL file. 
-- ** These commands were put in this file only as a convenience.

-- SET search_path TO pg_catalog,public;
-- ddl-end --

-- object: public.person | type: TABLE --
-- DROP TABLE IF EXISTS public.person CASCADE;
CREATE TABLE public.person (
	per_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	per_name varchar(100) NOT NULL,
    per_identity_document bigint NOT NULL,
	per_email varchar(100) NOT NULL,
    per_contact_number bigint NOT NULL,
	per_state varchar(15) NOT NULL DEFAULT 'activo',
	per_update_date timestamptz,
	CONSTRAINT "Person_pk" PRIMARY KEY (per_id),
	CONSTRAINT "Person_idocument_uq" UNIQUE (per_identity_document),
	CONSTRAINT "Person_email_uq" UNIQUE (per_email),
	CONSTRAINT "Person_state_ck" CHECK (per_state IN ('activo','inactivo','bloqueado'))
);
-- ddl-end --
COMMENT ON TABLE public.person IS E'Representa a la persona corriente';
-- ddl-end --
COMMENT ON COLUMN public.person.per_id IS E'Index, identificador de persona (este valor puede asignarse, pero en caso contrario incrementa automaticamente)';
-- ddl-end --
COMMENT ON COLUMN public.person.per_name IS E'Nombre de la persona';
-- ddl-end --
COMMENT ON COLUMN public.person.per_identity_document IS E'Numero del documento de ciudadania';
-- ddl-end --
COMMENT ON COLUMN public.person.per_email IS E'Correo electronico de la persona';
-- ddl-end --
COMMENT ON COLUMN public.person.per_contact_number IS E'Numero de telefono mobil';
-- ddl-end --
COMMENT ON COLUMN public.person.per_state IS E'Estado actual de la cuenta';
-- ddl-end --
COMMENT ON COLUMN public.person.per_update_date IS E'Fecha y hora en la cual se concreto una actualizacion de los datos de una persona';
-- ddl-end --
COMMENT ON CONSTRAINT "Person_pk" ON public.person IS E'Restriccion de identificador unico para persona';
-- ddl-end --
COMMENT ON CONSTRAINT "Person_idocument_uq" ON public.person IS E'Restriccion que impidela repeticion de un documento de identidad';
-- ddl-end --
COMMENT ON CONSTRAINT "Person_email_uq" ON public.person IS E'Restriccion que impide la repeticion de un correo electronico';
-- ddl-end --
COMMENT ON CONSTRAINT "Person_state_ck" ON public.person IS E'Un estado solo puede ser activo, inactivo o bloqueado';
-- ddl-end --
--ALTER TABLE public.person OWNER TO postgres;
-- ddl-end --

-- object: public.users | type: TABLE --
-- DROP TABLE IF EXISTS public.users CASCADE;
CREATE TABLE public.users (
	use_id integer NOT NULL,
	user_provider_id varchar(255) NOT NULL,
	user_provider_name varchar(25) NOT NULL,
	user_refresh_token varchar(255),
	CONSTRAINT "User_pk" PRIMARY KEY (use_id),
	CONSTRAINT "User_provider_uq" UNIQUE (user_provider_id,user_provider_name)
);
-- ddl-end --
COMMENT ON TABLE public.users IS E'Cuenta OAuth vinculada a una persona. Se crea cuando una persona con correo verificado inicia sesion por primera vez';
-- ddl-end --
COMMENT ON COLUMN public.users.use_id IS E'Index identificador del usuario (proviende de persona)';
-- ddl-end --
COMMENT ON COLUMN public.users.user_provider_id IS E'Identificador de identidad (sub) asignado por Auth0 y vinculado a la persona';
-- ddl-end --
COMMENT ON COLUMN public.users.user_provider_name IS E'El nombre del proovedor con el cual se hizo el inicio de sesion';
-- ddl-end --
COMMENT ON COLUMN public.users.user_refresh_token IS E'El hash bcrypt de nuestro JWT refresh token';
-- ddl-end --
COMMENT ON CONSTRAINT "User_pk" ON public.users IS E'Restriccion de identificador unico de usuario';
-- ddl-end --
COMMENT ON CONSTRAINT "User_provider_uq" ON public.users IS E'Restriccion que impide la repeticion de un id proovedor + nombre';
-- ddl-end --
--ALTER TABLE public.users OWNER TO postgres;
-- ddl-end --

-- object: public.psychologist | type: TABLE --
-- DROP TABLE IF EXISTS public.psychologist CASCADE;
CREATE TABLE public.psychologist (
	psy_id integer NOT NULL,
	psy_license_number integer NOT NULL,
	psy_speciality varchar(45) NOT NULL,
	CONSTRAINT "Psychologist_pk" PRIMARY KEY (psy_id)
);
-- ddl-end --
COMMENT ON TABLE public.psychologist IS E'Representa al usuario el cual tiene como rol psicologo';
-- ddl-end --
COMMENT ON COLUMN public.psychologist.psy_id IS E'Index, identificador del psicologo, proviene de usuario';
-- ddl-end --
COMMENT ON COLUMN public.psychologist.psy_license_number IS E'El numero de licencia medico profesional para psicologos';
-- ddl-end --
COMMENT ON COLUMN public.psychologist.psy_speciality IS E'Especialidad profesional del psicologo';
-- ddl-end --
COMMENT ON CONSTRAINT "Psychologist_pk" ON public.psychologist IS E'Restriccion de identificador unico de psicologo';
-- ddl-end --
--ALTER TABLE public.psychologist OWNER TO postgres;
-- ddl-end --

-- object: public.schedule | type: TABLE --
-- DROP TABLE IF EXISTS public.schedule CASCADE;
CREATE TABLE public.schedule (
	sch_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	psy_id integer NOT NULL,
	app_id integer,
	sch_date date NOT NULL,
	sch_start_time time NOT NULL,
	sch_end_time time NOT NULL,
	CONSTRAINT "Schedule_pk" PRIMARY KEY (sch_id),
	CONSTRAINT "Schedule_time_ck" CHECK (sch_end_time > sch_start_time)
);
-- ddl-end --
COMMENT ON TABLE public.schedule IS E'Representa las franjas horarias por la cual el psicologo esta ocupado';
-- ddl-end --
COMMENT ON COLUMN public.schedule.sch_id IS E'Index, identificador de la agenda o franja horaria (este valor puede asignarse, pero en caso contrario incrementa automaticamente)';
-- ddl-end --
COMMENT ON COLUMN public.schedule.psy_id IS E'Identificador del psicologo';
-- ddl-end --
COMMENT ON COLUMN public.schedule.app_id IS E'Identificador de la cita, en caso de que la razon de ocupacion sea por una';
-- ddl-end --
COMMENT ON COLUMN public.schedule.sch_date IS E'Fecha en la que el psicologo indica su indospinibilidad';
-- ddl-end --
COMMENT ON COLUMN public.schedule.sch_start_time IS E'Hora inicial en la que el psicologo indica su indospinibilidad';
-- ddl-end --
COMMENT ON COLUMN public.schedule.sch_end_time IS E'Hora final en la que el psicologo indica su indospinibilidad';
-- ddl-end --
COMMENT ON CONSTRAINT "Schedule_pk" ON public.schedule IS E'Restriccion de identificador unico de agenda';
-- ddl-end --
COMMENT ON CONSTRAINT "Schedule_time_ck" ON public.schedule IS E'Restriccion que obliga a que la hora de finalizacion sea posterior a la de inicio';
-- ddl-end --
--ALTER TABLE public.schedule OWNER TO postgres;
-- ddl-end --

-- object: public.appointments | type: TABLE --
-- DROP TABLE IF EXISTS public.appointments CASCADE;
CREATE TABLE public.appointments (
	app_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	psy_id integer NOT NULL,
	sec_id integer NOT NULL,
	req_id integer NOT NULL,
	app_patient_person_id integer,
	app_patient_dependent_id integer,
	app_date timestamptz NOT NULL,
	app_state varchar(15) NOT NULL,
	app_type varchar(15) NOT NULL,
	CONSTRAINT "Appointments_pk" PRIMARY KEY (app_id),
	CONSTRAINT "Appointment_pacient_ck" CHECK ((app_patient_person_id IS NOT NULL) OR (app_patient_dependent_id IS NOT NULL)
)
);
-- ddl-end --
COMMENT ON TABLE public.appointments IS E'Representa la planeacion para el planteamiento de la cita psicologica';
-- ddl-end --
COMMENT ON COLUMN public.appointments.app_id IS E'Index, identificador de la cita (este valor puede asignarse, pero en caso contrario incrementa automaticamente)';
-- ddl-end --
COMMENT ON COLUMN public.appointments.psy_id IS E'Identificador del psicologo';
-- ddl-end --
COMMENT ON COLUMN public.appointments.sec_id IS E'Identificador del secretario';
-- ddl-end --
COMMENT ON COLUMN public.appointments.req_id IS E'Identificador del consultante';
-- ddl-end --
COMMENT ON COLUMN public.appointments.app_patient_person_id IS E'Identificador del paciente si este es para el propio consultante';
-- ddl-end --
COMMENT ON COLUMN public.appointments.app_patient_dependent_id IS E'Identificador del paciente si este es para un dependiente (menor de edad) registrado por el consultante';
-- ddl-end --
COMMENT ON COLUMN public.appointments.app_date IS E'Fecha de cuando inicia la cita';
-- ddl-end --
COMMENT ON COLUMN public.appointments.app_state IS E'Estado actual de la cita';
-- ddl-end --
COMMENT ON COLUMN public.appointments.app_type IS E'Tipo de la cita';
-- ddl-end --
COMMENT ON CONSTRAINT "Appointments_pk" ON public.appointments IS E'Restriccion de identificador unico de cita';
-- ddl-end --
COMMENT ON CONSTRAINT "Appointment_pacient_ck" ON public.appointments IS E'Restriccion que obliga que exista un paciente, sea el consultante o el dependiente';
-- ddl-end --
--ALTER TABLE public.appointments OWNER TO postgres;
-- ddl-end --

-- object: public.rol | type: TABLE --
-- DROP TABLE IF EXISTS public.rol CASCADE;
CREATE TABLE public.rol (
	rol_id integer NOT NULL,
	rol_description varchar(25) NOT NULL,
	CONSTRAINT "Rol_pk" PRIMARY KEY (rol_id)
);
-- ddl-end --
COMMENT ON TABLE public.rol IS E'Clasificaccion de la persona la cual le brinda ciertos privilegios y responsabilidades';
-- ddl-end --
COMMENT ON COLUMN public.rol.rol_id IS E'Index, identificador de rol';
-- ddl-end --
COMMENT ON COLUMN public.rol.rol_description IS E'Descripcion o nombre del rol';
-- ddl-end --
COMMENT ON CONSTRAINT "Rol_pk" ON public.rol IS E'Restriccion de identificador unico de rol';
-- ddl-end --
--ALTER TABLE public.rol OWNER TO postgres;
-- ddl-end --

-- object: public.person_rol | type: TABLE --
-- DROP TABLE IF EXISTS public.person_rol CASCADE;
CREATE TABLE public.person_rol (
	per_id integer NOT NULL,
	rol_id integer NOT NULL,
	pr_assigned_at timestamptz NOT NULL,
	CONSTRAINT "Person_Roles_pk" PRIMARY KEY (per_id,rol_id)
);
-- ddl-end --
COMMENT ON TABLE public.person_rol IS E'Tabla intermedia que vincula las personas con su/sus rol/roles';
-- ddl-end --
COMMENT ON COLUMN public.person_rol.per_id IS E'Identificador de la persona';
-- ddl-end --
COMMENT ON COLUMN public.person_rol.rol_id IS E'Identificador del rol';
-- ddl-end --
COMMENT ON COLUMN public.person_rol.pr_assigned_at IS E'Fecha y hora de la asignacion de un rol a una persona';
-- ddl-end --
COMMENT ON CONSTRAINT "Person_Roles_pk" ON public.person_rol IS E'Restriccion de identificacion unico compuesto con la id de la persona y rol';
-- ddl-end --
--ALTER TABLE public.person_rol OWNER TO postgres;
-- ddl-end --

-- object: public.dependents | type: TABLE --
-- DROP TABLE IF EXISTS public.dependents CASCADE;
CREATE TABLE public.dependents (
	dep_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    dep_identity_document bigint NOT NULL,
	dep_name varchar(100) NOT NULL,
	dep_contact_number integer NOT NULL,
	dep_birthdate date NOT NULL,
	CONSTRAINT "Dependents_pk" PRIMARY KEY (dep_id),
	CONSTRAINT "Dependent_idocument_uq" UNIQUE (dep_identity_document)
);
-- ddl-end --
COMMENT ON TABLE public.dependents IS E'Personas menores de edad, dependientes de su tutor legal. Se modelan en una tabla separada de Person (y no como subtipo) porque sus datos requieren tratamiento especial bajo la normativa de proteccion de datos de menores';
-- ddl-end --
COMMENT ON COLUMN public.dependents.dep_id IS E'Index, identificador de dependiente (menor de edad) (este valor puede asignarse, pero en caso contrario incrementa automaticamente)';
-- ddl-end --
COMMENT ON COLUMN public.dependents.dep_identity_document IS E'Numero del documento de ciudadania';
-- ddl-end --
COMMENT ON COLUMN public.dependents.dep_name IS E'Nombre del dependiente';
-- ddl-end --
COMMENT ON COLUMN public.dependents.dep_contact_number IS E'Numero de telefono mobil del dependiente';
-- ddl-end --
COMMENT ON COLUMN public.dependents.dep_birthdate IS E'Fecha de nacimiento del dependiente';
-- ddl-end --
COMMENT ON CONSTRAINT "Dependents_pk" ON public.dependents IS E'Restriccion de identificador unico de dependiente';
-- ddl-end --
COMMENT ON CONSTRAINT "Dependent_idocument_uq" ON public.dependents IS E'Restriccion que impide la repeticion de los documentos de identidad';
-- ddl-end --
--ALTER TABLE public.dependents OWNER TO postgres;
-- ddl-end --

-- object: public.relationship | type: TABLE --
-- DROP TABLE IF EXISTS public.relationship CASCADE;
CREATE TABLE public.relationship (
	rel_id integer NOT NULL,
	rel_description varchar(25) NOT NULL,
	CONSTRAINT "Relationship_pk" PRIMARY KEY (rel_id)
);
-- ddl-end --
COMMENT ON TABLE public.relationship IS E'Tipos de relacion que tiene un menor de edad con su tutor legal';
-- ddl-end --
COMMENT ON COLUMN public.relationship.rel_id IS E'Index, identificador de relacion/parentesco';
-- ddl-end --
COMMENT ON COLUMN public.relationship.rel_description IS E'Descripcion o nombre del parentesco del consultante hacia el menor';
-- ddl-end --
COMMENT ON CONSTRAINT "Relationship_pk" ON public.relationship IS E'Identificador unico de la relacion';
-- ddl-end --
--ALTER TABLE public.relationship OWNER TO postgres;
-- ddl-end --

-- object: public.donors | type: TABLE --
-- DROP TABLE IF EXISTS public.donors CASCADE;
CREATE TABLE public.donors (
	dono_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	dono_total_amount numeric(20,2),
	dono_email varchar(100) NOT NULL,
	dono_last_donation_date date,
	CONSTRAINT "Donors_pk" PRIMARY KEY (dono_id),
	CONSTRAINT "Donor_email_uq" UNIQUE (dono_email)
);
-- ddl-end --
COMMENT ON TABLE public.donors IS E'Representa a la persona corriente la cual desea realizar una donacion';
-- ddl-end --
COMMENT ON COLUMN public.donors.dono_id IS E'Index, identificador del donador (este valor puede asignarse, pero en caso contrario incrementa automaticamente)';
-- ddl-end --
COMMENT ON COLUMN public.donors.dono_total_amount IS E'Atributo calculado, suma las donaciones realizadas';
-- ddl-end --
COMMENT ON COLUMN public.donors.dono_email IS E'Correo del donante, subministrado por la API de la pasarela de pagos';
-- ddl-end --
COMMENT ON COLUMN public.donors.dono_last_donation_date IS E'Fecha de la ultima donacion realizada';
-- ddl-end --
COMMENT ON CONSTRAINT "Donors_pk" ON public.donors IS E'Restriccion de identificador unico de donador';
-- ddl-end --
COMMENT ON CONSTRAINT "Donor_email_uq" ON public.donors IS E'Restriccion que impide la repeticion del correo de los donantes';
-- ddl-end --
--ALTER TABLE public.donors OWNER TO postgres;
-- ddl-end --

-- object: public.donations | type: TABLE --
-- DROP TABLE IF EXISTS public.donations CASCADE;
CREATE TABLE public.donations (
	dona_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	dono_id integer NOT NULL,
	pmet_id integer NOT NULL,
	dona_amount numeric(12,2) NOT NULL,
	dona_state varchar(10) NOT NULL,
	dona_description varchar(250),
	CONSTRAINT "Donations_pk" PRIMARY KEY (dona_id),
	CONSTRAINT "Donation_amount_ck" CHECK (dona_amount > 0)
);
-- ddl-end --
COMMENT ON TABLE public.donations IS E'Representa la donacion realizada por los donantes';
-- ddl-end --
COMMENT ON COLUMN public.donations.dona_id IS E'Index, identificador de la donacion (este valor puede asignarse, pero en caso contrario incrementa automaticamente)';
-- ddl-end --
COMMENT ON COLUMN public.donations.dono_id IS E'Identificador del donante';
-- ddl-end --
COMMENT ON COLUMN public.donations.pmet_id IS E'Identificador del metodo de pago';
-- ddl-end --
COMMENT ON COLUMN public.donations.dona_amount IS E'Cantidad donada';
-- ddl-end --
COMMENT ON COLUMN public.donations.dona_state IS E'Estado de la donacion dado por parte de la API';
-- ddl-end --
COMMENT ON COLUMN public.donations.dona_description IS E'Mensaje que puede ser dado por el donante';
-- ddl-end --
COMMENT ON CONSTRAINT "Donations_pk" ON public.donations IS E'Restriccion de identificador unico de las donaciones';
-- ddl-end --
COMMENT ON CONSTRAINT "Donation_amount_ck" ON public.donations IS E'Restriccion que obliga a que la cantidad donada sea superior a 0$';
-- ddl-end --
--ALTER TABLE public.donations OWNER TO postgres;
-- ddl-end --

-- object: public.payment_method | type: TABLE --
-- DROP TABLE IF EXISTS public.payment_method CASCADE;
CREATE TABLE public.payment_method (
	pmet_id integer NOT NULL,
	pmet_is_active boolean NOT NULL DEFAULT true,
	pmet_name varchar(25) NOT NULL,
	CONSTRAINT "Payment_Method_pk" PRIMARY KEY (pmet_id)
);
-- ddl-end --
COMMENT ON TABLE public.payment_method IS E'Representa al metodo de pago con el cual se puede realizar una donacion';
-- ddl-end --
COMMENT ON COLUMN public.payment_method.pmet_id IS E'Index, identificador del metodo de pago';
-- ddl-end --
COMMENT ON COLUMN public.payment_method.pmet_is_active IS E'Estado en el cual se indica si un metodo de pago puede ser usado';
-- ddl-end --
COMMENT ON COLUMN public.payment_method.pmet_name IS E'Nombre del servicio usado';
-- ddl-end --
COMMENT ON CONSTRAINT "Payment_Method_pk" ON public.payment_method IS E'Restriccion de identificador unico del metodo de pago';
-- ddl-end --
--ALTER TABLE public.payment_method OWNER TO postgres;
-- ddl-end --

-- object: public.requester_dependent | type: TABLE --
-- DROP TABLE IF EXISTS public.requester_dependent CASCADE;
CREATE TABLE public.requester_dependent (
	req_id integer NOT NULL,
	dep_id integer NOT NULL,
	rel_id integer,
	rd_assigned_at timestamptz NOT NULL,
	CONSTRAINT "Requester_Dependent_pk" PRIMARY KEY (req_id,dep_id)
);
-- ddl-end --
COMMENT ON TABLE public.requester_dependent IS E'Tabla intermedia, vincula los consultantes con los menores de edad segun su parentesco';
-- ddl-end --
COMMENT ON COLUMN public.requester_dependent.req_id IS E'Identificador del consultante';
-- ddl-end --
COMMENT ON COLUMN public.requester_dependent.dep_id IS E'Identificador del dependiente (menor de edad)';
-- ddl-end --
COMMENT ON COLUMN public.requester_dependent.rel_id IS E'Identificador de la relacion (parentesco)';
-- ddl-end --
COMMENT ON COLUMN public.requester_dependent.rd_assigned_at IS E'Fecha y hora en la que un consultante registro a un menor de idad y definio su parentesco con este';
-- ddl-end --
COMMENT ON CONSTRAINT "Requester_Dependent_pk" ON public.requester_dependent IS E'Restriccion Identificador unico que junta el id de un consultante y un dependiente';
-- ddl-end --
--ALTER TABLE public.requester_dependent OWNER TO postgres;
-- ddl-end --

-- object: "User_Person_fk" | type: CONSTRAINT --
-- ALTER TABLE public.users DROP CONSTRAINT IF EXISTS "User_Person_fk" CASCADE;
ALTER TABLE public.users ADD CONSTRAINT "User_Person_fk" FOREIGN KEY (use_id)
REFERENCES public.person (per_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "User_Person_fk" ON public.users IS E'Identificador proveniente de persona';
-- ddl-end --


-- object: "Psychologist_User_fk" | type: CONSTRAINT --
-- ALTER TABLE public.psychologist DROP CONSTRAINT IF EXISTS "Psychologist_User_fk" CASCADE;
ALTER TABLE public.psychologist ADD CONSTRAINT "Psychologist_User_fk" FOREIGN KEY (psy_id)
REFERENCES public.person (per_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Psychologist_User_fk" ON public.psychologist IS E'Identificador proveniente de persona (un psicologo puede existir antes de tener cuenta de usuario)';
-- ddl-end --


-- object: "Schedule_Psychologist_fk" | type: CONSTRAINT --
-- ALTER TABLE public.schedule DROP CONSTRAINT IF EXISTS "Schedule_Psychologist_fk" CASCADE;
ALTER TABLE public.schedule ADD CONSTRAINT "Schedule_Psychologist_fk" FOREIGN KEY (psy_id)
REFERENCES public.psychologist (psy_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Schedule_Psychologist_fk" ON public.schedule IS E'Identificador proveniente de psicologo';
-- ddl-end --


-- object: "Schedule_Appointment_fk" | type: CONSTRAINT --
-- ALTER TABLE public.schedule DROP CONSTRAINT IF EXISTS "Schedule_Appointment_fk" CASCADE;
ALTER TABLE public.schedule ADD CONSTRAINT "Schedule_Appointment_fk" FOREIGN KEY (app_id)
REFERENCES public.appointments (app_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Schedule_Appointment_fk" ON public.schedule IS E'Identificador proveniente de cita';
-- ddl-end --


-- object: "Appointment_Psychologist_fk" | type: CONSTRAINT --
-- ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS "Appointment_Psychologist_fk" CASCADE;
ALTER TABLE public.appointments ADD CONSTRAINT "Appointment_Psychologist_fk" FOREIGN KEY (psy_id)
REFERENCES public.psychologist (psy_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Appointment_Psychologist_fk" ON public.appointments IS E'Identificador proveniente del psicologo';
-- ddl-end --


-- object: "Appointment_Secretary_fk" | type: CONSTRAINT --
-- ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS "Appointment_Secretary_fk" CASCADE;
ALTER TABLE public.appointments ADD CONSTRAINT "Appointment_Secretary_fk" FOREIGN KEY (sec_id)
REFERENCES public.users (use_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Appointment_Secretary_fk" ON public.appointments IS E'Identificador proveniente de usuario (secretario)';
-- ddl-end --


-- object: "Appointment_Requester_fk" | type: CONSTRAINT --
-- ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS "Appointment_Requester_fk" CASCADE;
ALTER TABLE public.appointments ADD CONSTRAINT "Appointment_Requester_fk" FOREIGN KEY (req_id)
REFERENCES public.person (per_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Appointment_Requester_fk" ON public.appointments IS E'Identificador proveniente de persona (consultante)';
-- ddl-end --


-- object: "Appointment_Pacient_fk" | type: CONSTRAINT --
-- ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS "Appointment_Pacient_fk" CASCADE;
ALTER TABLE public.appointments ADD CONSTRAINT "Appointment_Pacient_fk" FOREIGN KEY (app_patient_person_id)
REFERENCES public.person (per_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Appointment_Pacient_fk" ON public.appointments IS E'Identificador proveniente de persona (consultante), implica que la cita es para el mismo consultante';
-- ddl-end --


-- object: "Appointment_Dependent_fk" | type: CONSTRAINT --
-- ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS "Appointment_Dependent_fk" CASCADE;
ALTER TABLE public.appointments ADD CONSTRAINT "Appointment_Dependent_fk" FOREIGN KEY (app_patient_dependent_id)
REFERENCES public.dependents (dep_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Appointment_Dependent_fk" ON public.appointments IS E'Identificador proveniente de dependiente, implica que la cita solicitada por el consultante es para este menor de edad';
-- ddl-end --


-- object: "PR_Person_fk" | type: CONSTRAINT --
-- ALTER TABLE public.person_rol DROP CONSTRAINT IF EXISTS "PR_Person_fk" CASCADE;
ALTER TABLE public.person_rol ADD CONSTRAINT "PR_Person_fk" FOREIGN KEY (per_id)
REFERENCES public.person (per_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "PR_Person_fk" ON public.person_rol IS E'Identificador proveniente de persona';
-- ddl-end --


-- object: "PR_Rol_fk" | type: CONSTRAINT --
-- ALTER TABLE public.person_rol DROP CONSTRAINT IF EXISTS "PR_Rol_fk" CASCADE;
ALTER TABLE public.person_rol ADD CONSTRAINT "PR_Rol_fk" FOREIGN KEY (rol_id)
REFERENCES public.rol (rol_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "PR_Rol_fk" ON public.person_rol IS E'Identificador proveniente de rol';
-- ddl-end --


-- object: "Donation_Donor_fk" | type: CONSTRAINT --
-- ALTER TABLE public.donations DROP CONSTRAINT IF EXISTS "Donation_Donor_fk" CASCADE;
ALTER TABLE public.donations ADD CONSTRAINT "Donation_Donor_fk" FOREIGN KEY (dono_id)
REFERENCES public.donors (dono_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Donation_Donor_fk" ON public.donations IS E'Identificador proveniente del donante';
-- ddl-end --


-- object: "Donation_PMethod_fk" | type: CONSTRAINT --
-- ALTER TABLE public.donations DROP CONSTRAINT IF EXISTS "Donation_PMethod_fk" CASCADE;
ALTER TABLE public.donations ADD CONSTRAINT "Donation_PMethod_fk" FOREIGN KEY (pmet_id)
REFERENCES public.payment_method (pmet_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "Donation_PMethod_fk" ON public.donations IS E'Identificador que proviene del metodo de pago';
-- ddl-end --


-- object: "RD_Requester_fk" | type: CONSTRAINT --
-- ALTER TABLE public.requester_dependent DROP CONSTRAINT IF EXISTS "RD_Requester_fk" CASCADE;
ALTER TABLE public.requester_dependent ADD CONSTRAINT "RD_Requester_fk" FOREIGN KEY (req_id)
REFERENCES public.person (per_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "RD_Requester_fk" ON public.requester_dependent IS E'Identificador proveniente de persona (consultante)';
-- ddl-end --


-- object: "RD_Dependent_fk" | type: CONSTRAINT --
-- ALTER TABLE public.requester_dependent DROP CONSTRAINT IF EXISTS "RD_Dependent_fk" CASCADE;
ALTER TABLE public.requester_dependent ADD CONSTRAINT "RD_Dependent_fk" FOREIGN KEY (dep_id)
REFERENCES public.dependents (dep_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "RD_Dependent_fk" ON public.requester_dependent IS E'Identificador proveniente de dependiente';
-- ddl-end --


-- object: "RD_Relationship_fk" | type: CONSTRAINT --
-- ALTER TABLE public.requester_dependent DROP CONSTRAINT IF EXISTS "RD_Relationship_fk" CASCADE;
ALTER TABLE public.requester_dependent ADD CONSTRAINT "RD_Relationship_fk" FOREIGN KEY (rel_id)
REFERENCES public.relationship (rel_id) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --
COMMENT ON CONSTRAINT "RD_Relationship_fk" ON public.requester_dependent IS E'Identificador proveniente de relacion (parentesco)';
-- ddl-end --

------------------------- MIGRATION 11/09/2026 -------------------------

ALTER TABLE public.person
    ALTER COLUMN per_identity_document DROP NOT NULL,
    ALTER COLUMN per_contact_number DROP NOT NULL;

ALTER TABLE public.person
    DROP CONSTRAINT IF EXISTS "Person_state_ck";

ALTER TABLE public.person
    ADD CONSTRAINT "Person_state_ck"
    CHECK (per_state IN ('activo', 'inactivo', 'bloqueado', 'pendiente'));

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS user_last_login_at timestamptz;

CREATE TABLE IF NOT EXISTS public.auth_sessions (
    auth_session_id uuid PRIMARY KEY,
    use_id integer NOT NULL,
    auth_session_refresh_token_hash varchar(255) NOT NULL,
    auth_session_last_activity_at timestamptz NOT NULL DEFAULT now(),
    auth_session_expires_at timestamptz NOT NULL,
    auth_session_revoked_at timestamptz,
    auth_session_created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Auth_Session_user_fk"
        FOREIGN KEY (use_id) REFERENCES public.users (use_id)
);

CREATE INDEX IF NOT EXISTS "Person_email_idx"
    ON public.person (lower(per_email));

CREATE INDEX IF NOT EXISTS "Auth_Session_user_idx"
    ON public.auth_sessions (use_id);

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS user_refresh_token varchar(255);

COMMENT ON COLUMN public.users.user_refresh_token
    IS E'El hash bcrypt de nuestro JWT refresh token';

------------------------- MIGRATION 14/09/2026 -------------------------
-- HU-1.3: un usuario puede tener varios roles a la vez, cada uno activable
-- o desactivable por separado sin perder la asignacion (lo que ya construyo
-- el frontend en feat/auth-states). person_rol solo tenia per_id+rol_id.
ALTER TABLE public.person_rol
    ADD COLUMN IF NOT EXISTS pr_active boolean NOT NULL DEFAULT true;

COMMENT ON COLUMN public.person_rol.pr_active
    IS E'Indica si el rol asignado esta activo (se puede desactivar sin quitarlo)';

-- per_contact_number en integer se desborda con cualquier celular colombiano
-- real (3xxxxxxxxx > 2147483647, el maximo de int4). Se amplia a bigint;
-- es un ensanchamiento seguro, no hay perdida de datos.
ALTER TABLE public.person
    ALTER COLUMN per_contact_number TYPE bigint;
ALTER TABLE public.person
    ALTER COLUMN per_identity_document TYPE bigint;
ALTER TABLE public.dependents
    ALTER COLUMN dep_identity_document TYPE bigint;
-- Identity documents are identifiers (up to 12 digits), so keep their bigint
-- values as strings in the application rather than converting through int4.
---- Modifications 14/09/2026 ----

COMMENT ON COLUMN public.users.user_last_login_at
    IS E'Fecha y hora del ultimo inicio de sesion exitoso del usuario a traves de OAuth';

CREATE TABLE IF NOT EXISTS public.security_access_log (
    security_access_log_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    use_id integer NOT NULL,
    auth_session_id uuid,
    security_access_log_section varchar(100) NOT NULL,
    security_access_log_message varchar(255) NOT NULL,
    security_access_log_created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Security_Access_Log_pk" PRIMARY KEY (security_access_log_id),
    CONSTRAINT "Security_Access_Log_User_fk" FOREIGN KEY (use_id)
        REFERENCES public.users (use_id) MATCH SIMPLE
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Security_Access_Log_Session_fk" FOREIGN KEY (auth_session_id)
        REFERENCES public.auth_sessions (auth_session_id) MATCH SIMPLE
        ON DELETE SET NULL ON UPDATE NO ACTION
);
 
COMMENT ON TABLE public.security_access_log
    IS E'Registro de seguridad: avisos generados por el sistema cuando un usuario intenta acceder a una seccion para la cual no tiene permisos';
COMMENT ON COLUMN public.security_access_log.security_access_log_id
    IS E'Index, identificador del registro de seguridad (incrementa automaticamente)';
COMMENT ON COLUMN public.security_access_log.use_id
    IS E'Identificador del usuario que intento acceder a la seccion no autorizada';
COMMENT ON COLUMN public.security_access_log.auth_session_id
    IS E'Identificador de la sesion activa desde la cual se genero el intento (opcional)';
COMMENT ON COLUMN public.security_access_log.security_access_log_section
    IS E'Seccion, ruta o recurso al cual el usuario intento acceder sin autorizacion';
COMMENT ON COLUMN public.security_access_log.security_access_log_message
    IS E'Mensaje o aviso generado por el sistema al detectar el intento de acceso no autorizado';
COMMENT ON COLUMN public.security_access_log.security_access_log_created_at
    IS E'Fecha y hora en la que se genero el aviso de seguridad';
 
COMMENT ON CONSTRAINT "Security_Access_Log_pk" ON public.security_access_log
    IS E'Restriccion de identificador unico del registro de seguridad';
COMMENT ON CONSTRAINT "Security_Access_Log_User_fk" ON public.security_access_log
    IS E'Identificador proveniente de usuario, indica quien intento el acceso no autorizado';
COMMENT ON CONSTRAINT "Security_Access_Log_Session_fk" ON public.security_access_log
    IS E'Identificador proveniente de la sesion de autenticacion activa durante el intento';
 
CREATE INDEX IF NOT EXISTS "Security_Access_Log_user_idx"
    ON public.security_access_log (use_id);
 
CREATE INDEX IF NOT EXISTS "Security_Access_Log_created_idx"
    ON public.security_access_log (security_access_log_created_at);

ALTER TABLE public.donations
    DROP CONSTRAINT IF EXISTS "Donation_state_ck";
 
ALTER TABLE public.donations
    ADD CONSTRAINT "Donation_state_ck"
    CHECK (dona_state IN ('PENDING', 'APPROVED', 'DECLINED', 'VOIDED', 'ERROR'));
 
COMMENT ON CONSTRAINT "Donation_state_ck" ON public.donations
    IS E'Restringe dona_state a los estados posibles de una transaccion de Wompi';
 
CREATE OR REPLACE FUNCTION public.fn_update_donor_total_amount()
RETURNS trigger AS $$
DECLARE
    v_dono_id integer;
BEGIN
    IF TG_OP = 'DELETE' THEN
        v_dono_id := OLD.dono_id;
    ELSE
        v_dono_id := NEW.dono_id;
    END IF;
 
    UPDATE public.donors
       SET dono_total_amount = (
                SELECT COALESCE(SUM(dona_amount), 0)
                  FROM public.donations
                 WHERE dono_id = v_dono_id
                   AND dona_state = 'APPROVED'
           )
     WHERE dono_id = v_dono_id;
 
    IF TG_OP = 'UPDATE' AND OLD.dono_id IS DISTINCT FROM NEW.dono_id THEN
        UPDATE public.donors
           SET dono_total_amount = (
                    SELECT COALESCE(SUM(dona_amount), 0)
                      FROM public.donations
                     WHERE dono_id = OLD.dono_id
                       AND dona_state = 'APPROVED'
               )
         WHERE dono_id = OLD.dono_id;
    END IF;
 
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;
 
DROP TRIGGER IF EXISTS trg_donations_update_donor_total ON public.donations;
 
CREATE TRIGGER trg_donations_update_donor_total
AFTER INSERT OR UPDATE OF dona_amount, dona_state, dono_id OR DELETE
ON public.donations
FOR EACH ROW
EXECUTE FUNCTION public.fn_update_donor_total_amount();
 
COMMENT ON FUNCTION public.fn_update_donor_total_amount()
    IS E'Recalcula donors.dono_total_amount como la suma de las donaciones completadas del donante, tras cada insercion, actualizacion o borrado en donations';

---- Testing ----

ALTER TABLE public.auth_sessions
    ALTER COLUMN auth_session_id SET DEFAULT gen_random_uuid();
 
ALTER TABLE public.auth_sessions
    ADD COLUMN IF NOT EXISTS auth_session_previous_token_hash varchar(255);
 
ALTER TABLE public.auth_sessions
    ADD COLUMN IF NOT EXISTS auth_session_revoked_reason varchar(20);
 
ALTER TABLE public.auth_sessions
    DROP CONSTRAINT IF EXISTS "Auth_Session_revoked_reason_ck";
 
ALTER TABLE public.auth_sessions
    ADD CONSTRAINT "Auth_Session_revoked_reason_ck"
    CHECK (auth_session_revoked_reason IS NULL OR auth_session_revoked_reason IN
        ('logout', 'rotated', 'reuse_detected', 'expired', 'admin'));
 
COMMENT ON COLUMN public.auth_sessions.auth_session_previous_token_hash
    IS E'Hash del refresh token inmediatamente anterior al actual (el que se reemplazo en la ultima rotacion). Si un token entrante coincide con este valor, es un intento de reuso y la sesion debe revocarse de inmediato';
COMMENT ON COLUMN public.auth_sessions.auth_session_revoked_reason
    IS E'Motivo de revocacion: logout, rotated (reemplazada por rotacion normal, no implica riesgo), reuse_detected (posible robo de token, requiere forzar re-login), expired o admin';
COMMENT ON CONSTRAINT "Auth_Session_revoked_reason_ck" ON public.auth_sessions
    IS E'Restringe el motivo de revocacion a valores conocidos';

----

ALTER TABLE public.users
    DROP COLUMN IF EXISTS user_refresh_token;

CREATE OR REPLACE FUNCTION public.fn_cleanup_expired_sessions(p_retention_days integer DEFAULT 30)
RETURNS integer AS $$
DECLARE
    v_deleted_count integer;
BEGIN
    DELETE FROM public.auth_sessions
     WHERE (auth_session_revoked_at IS NOT NULL AND auth_session_revoked_at < now() - (p_retention_days || ' days')::interval)
        OR (auth_session_expires_at < now() - (p_retention_days || ' days')::interval);

    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RETURN v_deleted_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.fn_cleanup_expired_sessions(integer)
    IS E'Purga sesiones de autenticacion revocadas o expiradas que superan el periodo de retencion en dias (por defecto 30 dias)';

CREATE OR REPLACE FUNCTION public.fn_cleanup_old_security_logs(p_retention_days integer DEFAULT 180)
RETURNS integer AS $$
DECLARE
    v_deleted_count integer;
BEGIN
    DELETE FROM public.security_access_log
     WHERE security_access_log_created_at < now() - (p_retention_days || ' days')::interval;

    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RETURN v_deleted_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.fn_cleanup_old_security_logs(integer)
    IS E'Purga registros de auditoria de seguridad que superan el periodo de retencion en dias (por defecto 180 dias) para cumplir con minimizacion de datos';


-------------------------------------------------------------------
-- MIGRACIÓN: 
-------------------------------------------------------------------

DO $$
DECLARE
  fk_name text;
BEGIN
  SELECT conname INTO fk_name
  FROM pg_constraint
  WHERE conrelid = 'public.security_access_log'::regclass
    AND confrelid = 'public.auth_sessions'::regclass
    AND contype = 'f';

  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.security_access_log DROP CONSTRAINT %I', fk_name);
  END IF;
END $$;

ALTER TABLE public.security_access_log
    DROP COLUMN IF EXISTS auth_session_id;

DROP FUNCTION IF EXISTS public.fn_cleanup_expired_sessions;

DROP TABLE IF EXISTS public.auth_sessions;

DROP TABLE IF EXISTS public.access_requests;

ALTER TABLE public.person
    DROP CONSTRAINT IF EXISTS "Person_email_uq";

DROP INDEX IF EXISTS "Person_email_idx";

CREATE UNIQUE INDEX "Person_email_uq" ON public.person (lower(per_email));

COMMENT ON INDEX public."Person_email_uq"
    IS E'Unicidad y busqueda case-insensitive del correo; evita duplicar persona por diferencias de mayusculas entre proveedores OAuth';

ALTER TABLE public.person
    ADD COLUMN IF NOT EXISTS per_created_by integer REFERENCES public.users(use_id),
    ADD COLUMN IF NOT EXISTS per_created_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE public.users
    DROP CONSTRAINT IF EXISTS "User_provider_uq";

ALTER TABLE public.users
    ADD CONSTRAINT "User_provider_uq" UNIQUE (user_provider_id);

COMMENT ON CONSTRAINT "User_provider_uq" ON public.users
    IS E'Garantiza unicidad global del sub entregado por Auth0; ya no depende de provider_name, que se conserva solo con fines informativos/filtrado';

ALTER TABLE public.users
    ADD COLUMN IF NOT EXISTS user_email_verified boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.users.user_email_verified
    IS E'Indica que la identidad Auth0 vinculada se autentico con un correo verificado';

-- Changes 21/09/2026 --- QA ok

ALTER TABLE public.dependents
    DROP COLUMN dep_contact_number;

-- ? NOTAS CLINICAS --- QA ok

CREATE TABLE IF NOT EXISTS public.clinical_notes (
    cn_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app_id integer NOT NULL,
    psy_id integer NOT NULL,
    cn_observation text NOT NULL,
    cn_created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Clinical_Notes_pk" PRIMARY KEY (cn_id),
    CONSTRAINT "Clinical_Notes_Appointment_fk" FOREIGN KEY (app_id)
        REFERENCES public.appointments (app_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Clinical_Notes_Psychologist_fk" FOREIGN KEY (psy_id)
        REFERENCES public.psychologist (psy_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

COMMENT ON TABLE public.clinical_notes
    IS E'Notas/observaciones clinicas que un psicologo registra sobre una cita puntual. El paciente (consultante o dependiente) se obtiene de la cita referenciada, no se duplica aqui';
COMMENT ON COLUMN public.clinical_notes.cn_id
    IS E'Index, identificador de la nota clinica (incrementa automaticamente)';
COMMENT ON COLUMN public.clinical_notes.app_id
    IS E'Identificador de la cita a la que corresponde la nota; de ahi se deriva el paciente (person o dependent) y el consultante';
COMMENT ON COLUMN public.clinical_notes.psy_id
    IS E'Identificador del psicologo autor de la nota (puede diferir del psy_id de la cita, ej. interconsulta o supervision)';
COMMENT ON COLUMN public.clinical_notes.cn_observation
    IS E'Texto libre de la observacion clinica; tipo text, sin limite practico de longitud';
COMMENT ON COLUMN public.clinical_notes.cn_created_at
    IS E'Fecha y hora en la que se registro la nota';

CREATE INDEX IF NOT EXISTS "Clinical_Notes_appointment_idx" ON public.clinical_notes (app_id);
CREATE INDEX IF NOT EXISTS "Clinical_Notes_psychologist_idx" ON public.clinical_notes (psy_id);

-- ? MARKETING --- QA ok

CREATE TABLE IF NOT EXISTS public.content_items (
    ci_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ci_key varchar(100) NOT NULL,
    ci_type varchar(10) NOT NULL,
    ci_text_value text,
    ci_image_url varchar(500),
    ci_image_alt varchar(150),
    mar_id integer NOT NULL,
    ci_updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Content_Items_pk" PRIMARY KEY (ci_id),
    CONSTRAINT "Content_Items_key_uq" UNIQUE (ci_key),
    CONSTRAINT "Content_Items_type_ck" CHECK (ci_type IN ('text','image')),
    CONSTRAINT "Content_Items_value_ck" CHECK (
        (ci_type = 'text'  AND ci_text_value IS NOT NULL AND ci_image_url IS NULL)
        OR
        (ci_type = 'image' AND ci_image_url IS NOT NULL AND ci_text_value IS NULL)
    ),
    CONSTRAINT "Content_Items_User_fk" FOREIGN KEY (mar_id)
        REFERENCES public.users (use_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

COMMENT ON TABLE public.content_items
    IS E'Contenido editable (textos e imagenes) que el rol marketing puede modificar sin requerir despliegue de codigo';
COMMENT ON COLUMN public.content_items.ci_key
    IS E'Identificador estable usado por el frontend para referenciar este contenido (ej. landing.hero.title, landing.hero.image)';
COMMENT ON COLUMN public.content_items.ci_type
    IS E'Tipo de contenido: text o image';
COMMENT ON COLUMN public.content_items.ci_text_value
    IS E'Valor del texto, si ci_type = text';
COMMENT ON COLUMN public.content_items.ci_image_url
    IS E'URL de la imagen en el bucket/CDN, si ci_type = image. No se almacena el binario en la BD';
COMMENT ON COLUMN public.content_items.ci_image_alt
    IS E'Texto alternativo de accesibilidad para la imagen, solo aplica si ci_type = image';
COMMENT ON COLUMN public.content_items.mar_id
    IS E'Usuario (rol marketing) que realizo la ultima modificacion';
COMMENT ON COLUMN public.content_items.ci_updated_at
    IS E'Fecha y hora de la ultima modificacion';

CREATE INDEX IF NOT EXISTS "Content_Items_key_idx" ON public.content_items (ci_key);

-- ========================= MIGRATION 21/09/2026 =========================
-- Módulo de citas psicológicas (appointments)
-- La cita nace de la solicitud pública del consultante. Este puede reclamar
-- posteriormente su cuenta con Auth0; users.use_id mantiene la relacion con
-- la persona que ya fue registrada al solicitar la cita.
-- El secretario es quien, al confirmar, asigna psicólogo, fecha y queda
-- registrado como sec_id. Por eso ambas FK son nullable en la creación.
-- ========================================================================

-- psy_id, sec_id y app_date son NULL hasta que el secretario confirma la cita
ALTER TABLE public.appointments
    ALTER COLUMN psy_id DROP NOT NULL,
    ALTER COLUMN sec_id DROP NOT NULL,
    ALTER COLUMN app_date DROP NOT NULL;

-- Motivo de consulta opcional indicado por el consultante
ALTER TABLE public.appointments
    ADD COLUMN IF NOT EXISTS app_reason text;

ALTER TABLE public.schedule
    ADD COLUMN IF NOT EXISTS sch_reason varchar(255);

COMMENT ON COLUMN public.schedule.sch_reason
    IS E'Motivo del bloqueo de agenda registrado por el psicologo, por ejemplo trabajo externo';

CREATE TABLE IF NOT EXISTS public.schedule_recurring_blocks (
    srb_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    psy_id integer NOT NULL,
    srb_day_of_week smallint NOT NULL,
    srb_start_time time NOT NULL,
    srb_end_time time NOT NULL,
    srb_valid_from date NOT NULL,
    srb_valid_until date,
    srb_reason varchar(255),
    srb_active boolean NOT NULL DEFAULT true,
    CONSTRAINT "Schedule_Recurring_Block_pk" PRIMARY KEY (srb_id),
    CONSTRAINT "Schedule_Recurring_Block_Day_ck" CHECK (srb_day_of_week BETWEEN 1 AND 7),
    CONSTRAINT "Schedule_Recurring_Block_Time_ck" CHECK (srb_end_time > srb_start_time),
    CONSTRAINT "Schedule_Recurring_Block_Date_ck" CHECK (
        srb_valid_until IS NULL OR srb_valid_until >= srb_valid_from
    ),
    CONSTRAINT "Schedule_Recurring_Block_Psychologist_fk" FOREIGN KEY (psy_id)
        REFERENCES public.psychologist (psy_id)
);

CREATE INDEX IF NOT EXISTS "Schedule_Recurring_Block_Psychologist_idx"
    ON public.schedule_recurring_blocks (psy_id, srb_day_of_week, srb_active);

-- Motivo interno de descarte de una solicitud
ALTER TABLE public.appointments
    ADD COLUMN IF NOT EXISTS app_discard_reason text;

-- Fecha y hora en que se registró la solicitud
ALTER TABLE public.appointments
    ADD COLUMN IF NOT EXISTS app_created_at timestamptz NOT NULL DEFAULT now();

-- Estados válidos del ciclo de vida de una cita
ALTER TABLE public.appointments
    DROP CONSTRAINT IF EXISTS "Appointment_state_ck";

ALTER TABLE public.appointments
    ADD CONSTRAINT "Appointment_state_ck"
    CHECK (app_state IN ('pendiente', 'asignada', 'confirmada', 'descartada', 'cancelada', 'realizada'));

-- Tipos de modalidad
ALTER TABLE public.appointments
    DROP CONSTRAINT IF EXISTS "Appointment_type_ck";

ALTER TABLE public.appointments
    ADD CONSTRAINT "Appointment_type_ck"
    CHECK (app_type IN ('presencial', 'virtual'));

COMMENT ON COLUMN public.appointments.app_reason
    IS E'Motivo de consulta opcional indicado por el consultante al hacer la solicitud';
COMMENT ON COLUMN public.appointments.app_discard_reason
    IS E'Motivo interno indicado por la asistente, o motivo automatico cuando el consultante retira una solicitud no confirmada';
COMMENT ON COLUMN public.appointments.app_created_at
    IS E'Fecha y hora en que el consultante registró la solicitud de cita';
COMMENT ON CONSTRAINT "Appointment_state_ck" ON public.appointments
    IS E'Estados: pendiente/asignada (solicitud no confirmada), confirmada, descartada (solicitud rechazada antes de confirmar), cancelada (cita confirmada que se anulo), realizada (atencion completada)';
COMMENT ON CONSTRAINT "Appointment_type_ck" ON public.appointments
    IS E'Modalidad de la cita: presencial o virtual';

-- Índices para consultas frecuentes
CREATE INDEX IF NOT EXISTS "Appointment_state_idx"   ON public.appointments (app_state);
CREATE INDEX IF NOT EXISTS "Appointment_req_idx"     ON public.appointments (req_id);
CREATE INDEX IF NOT EXISTS "Appointment_psy_idx"     ON public.appointments (psy_id);
CREATE INDEX IF NOT EXISTS "Appointment_created_idx" ON public.appointments (app_created_at);
CREATE INDEX IF NOT EXISTS "Appointment_patient_person_completed_idx"
        ON public.appointments (app_patient_person_id, app_date, app_id)
        WHERE app_patient_person_id IS NOT NULL
            AND app_state = 'realizada'
            AND psy_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS "Appointment_patient_dependent_completed_idx"
        ON public.appointments (app_patient_dependent_id, app_date, app_id)
        WHERE app_patient_dependent_id IS NOT NULL
            AND app_state = 'realizada'
            AND psy_id IS NOT NULL;

DROP TABLE IF EXISTS public.appointment_assignment_history;

-- Agregar en Appointments duracion de la cita
ALTER TABLE public.appointments
    ADD COLUMN IF NOT EXISTS app_duration integer;

COMMENT ON COLUMN public.appointments.app_duration
    IS E'Duracion de la cita en minutos';

-- Agregar en person fecha de nacimiento
ALTER TABLE public.person
    ADD COLUMN IF NOT EXISTS per_birthdate date;

COMMENT ON COLUMN public.person.per_birthdate
    IS E'Fecha de nacimiento de la persona';

-- Agregar en person sexo
ALTER TABLE public.person
    ADD COLUMN IF NOT EXISTS per_gender char(1);

ALTER TABLE public.person
    DROP CONSTRAINT IF EXISTS person_gender_ck;

ALTER TABLE public.person
    ADD CONSTRAINT person_gender_ck
    CHECK (per_gender IN ('F', 'M', 'O', 'P'));

COMMENT ON COLUMN public.person.per_gender
    IS E'Sexo de la persona: F=Femenino, M=Masculino, O=Otros, P=Prefiero no definir';

-- Agregar en dependents sexo
ALTER TABLE public.dependents
    ADD COLUMN IF NOT EXISTS dep_gender char(1);

ALTER TABLE public.dependents
    DROP CONSTRAINT IF EXISTS dependents_gender_ck;

ALTER TABLE public.dependents
    ADD CONSTRAINT dependents_gender_ck
    CHECK (dep_gender IN ('F', 'M', 'O', 'P'));

COMMENT ON COLUMN public.dependents.dep_gender
    IS E'Sexo del dependiente: F=Femenino, M=Masculino, O=Otros, P=Prefiero no definir';

-- Agregar tipo de tarjeta de identidad incluye CC, TI y CE
ALTER TABLE public.person
    ADD COLUMN IF NOT EXISTS per_card_type varchar(20);

ALTER TABLE public.person
    ADD CONSTRAINT "person_card_type_ck"
    CHECK (per_card_type IN ('CC', 'TI', 'CE'));

COMMENT ON COLUMN public.person.per_card_type
    IS E'Tipo de tarjeta de identidad: CC, TI, CE';

-- Agregar motivo de consulta a appointments
ALTER TABLE public.appointments
    ADD COLUMN IF NOT EXISTS app_reason text;

COMMENT ON COLUMN public.appointments.app_reason
    IS E'Motivo de consulta: texto proporcionado por el paciente al solicitar la cita';

-- Agregar checkbox aceptacion de terminos y condiciones de nota clinica
ALTER TABLE public.clinical_notes
    ADD COLUMN IF NOT EXISTS cn_termns_accpted boolean DEFAULT false;

COMMENT ON COLUMN public.clinical_notes.cn_termns_accpted
    IS E'Checkbox aceptacion de terminos y condiciones de nota clinica';

-- Agregar checkbox aceptacion de terminos y condiciones de personas
ALTER TABLE public.person
    ADD COLUMN IF NOT EXISTS per_termns_accpted boolean DEFAULT false,
    ADD COLUMN IF NOT EXISTS per_policy_accepted_at timestamptz,
    ADD COLUMN IF NOT EXISTS per_policy_version varchar(50);

COMMENT ON COLUMN public.person.per_termns_accpted
    IS E'Checkbox aceptacion de terminos y condiciones de persona';
COMMENT ON COLUMN public.person.per_policy_accepted_at
    IS E'Fecha y hora en la que la persona acepto la politica vigente de tratamiento de datos para este formulario';
COMMENT ON COLUMN public.person.per_policy_version
    IS E'Version de la politica de tratamiento de datos que fue aceptada por la persona en el momento del formulario';

-- Agregar checkbox aceptacion de terminos y condiciones de dependientes
ALTER TABLE public.dependents
    ADD COLUMN IF NOT EXISTS dep_termns_accpted boolean DEFAULT false,
    ADD COLUMN IF NOT EXISTS dep_policy_accepted_at timestamptz,
    ADD COLUMN IF NOT EXISTS dep_policy_version varchar(50);

COMMENT ON COLUMN public.dependents.dep_termns_accpted
    IS E'Checkbox aceptacion de terminos y condiciones de dependiente';
COMMENT ON COLUMN public.dependents.dep_policy_accepted_at
    IS E'Fecha y hora en la que el responsable del menor acepto la politica vigente de tratamiento de datos para este formulario';
COMMENT ON COLUMN public.dependents.dep_policy_version
    IS E'Version de la politica de tratamiento de datos que fue aceptada por el responsable del menor en el momento del formulario';

-- Agregar tabla auditoria nota clinica del psicologo
CREATE TABLE IF NOT EXISTS public.clinical_notes_audit (
    cna_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cn_id integer NOT NULL,
    psy_id integer NOT NULL,
    cna_date timestamptz NOT NULL,
    cna_ip_address varchar(50) NOT NULL,
    CONSTRAINT "Clinical_Notes_Audit_pk" PRIMARY KEY (cna_id),
    CONSTRAINT "Clinical_Notes_Audit_Nota_fk" FOREIGN KEY (cn_id)
        REFERENCES public.clinical_notes (cn_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Clinical_Notes_Audit_Psicologo_fk" FOREIGN KEY (psy_id)
        REFERENCES public.psychologist (psy_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

COMMENT ON TABLE public.clinical_notes_audit
    IS E'Tabla auditoria nota clinica del psicologo';

COMMENT ON COLUMN public.clinical_notes_audit.cna_id
    IS E'Identificador de la auditoria';

COMMENT ON COLUMN public.clinical_notes_audit.cn_id
    IS E'Identificador de la nota clinica';

COMMENT ON COLUMN public.clinical_notes_audit.psy_id
    IS E'Identificador del psicologo';

COMMENT ON COLUMN public.clinical_notes_audit.cna_date
    IS E'Fecha y hora de la auditoria';

COMMENT ON COLUMN public.clinical_notes_audit.cna_ip_address
    IS E'Direccion IP del psicologo';

-- Agregar checkbox aceptacion de terminos y condiciones del psicologo para la cracion de agendas
ALTER TABLE public.psychologist
    ADD COLUMN IF NOT EXISTS psy_termns_accpted boolean DEFAULT false,
    ADD COLUMN IF NOT EXISTS psy_policy_accepted_at timestamptz,
    ADD COLUMN IF NOT EXISTS psy_policy_version varchar(50);

COMMENT ON COLUMN public.psychologist.psy_termns_accpted
    IS E'Checkbox aceptacion de terminos y condiciones del psicologo';
COMMENT ON COLUMN public.psychologist.psy_policy_accepted_at
    IS E'Fecha y hora en la que el psicologo acepto la politica vigente de tratamiento de datos para la creacion de su agenda';
COMMENT ON COLUMN public.psychologist.psy_policy_version
    IS E'Version de la politica de tratamiento de datos que fue aceptada por el psicologo en el momento de registrar su disponibilidad';

------------------------- MIGRATION 26/09/2026 -------------------------
-- HU-2.1: Gestión de fichas de consultantes por asistente administrativa
-- Agregar campo de zona de residencia como texto para caracterización de población
-------------------------------------------------------------------

-- Agregar campo de municipio a la tabla person como texto
ALTER TABLE public.person
    ADD COLUMN IF NOT EXISTS per_municipality varchar(100);

COMMENT ON COLUMN public.person.per_municipality
    IS E'Municipio de residencia del consultante';

-- Agregar campo de departamento a la tabla person como texto
ALTER TABLE public.person
    ADD COLUMN IF NOT EXISTS per_department varchar(100);

COMMENT ON COLUMN public.person.per_department
    IS E'Departamento de residencia del consultante';


------------------------- MIGRATION 26/09/2026 (Parte 2) -------------------------
-- HU-2.3: Historial de cambios de asignación de psicólogos y racha de citas
-- Tabla para registrar cambios de asignación de psicólogos a citas
-------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.appointment_assignment_history (
    aah_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app_id integer NOT NULL,
    old_psy_id integer,
    new_psy_id integer NOT NULL,
    sec_id integer NOT NULL,
    aah_changed_at timestamptz NOT NULL DEFAULT now(),
    aah_reason varchar(255),
    CONSTRAINT "Appointment_Assignment_History_pk" PRIMARY KEY (aah_id),
    CONSTRAINT "Appointment_Assignment_History_Appointment_fk" FOREIGN KEY (app_id)
        REFERENCES public.appointments (app_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Appointment_Assignment_History_Old_Psychologist_fk" FOREIGN KEY (old_psy_id)
        REFERENCES public.psychologist (psy_id)
        ON DELETE SET NULL ON UPDATE NO ACTION,
    CONSTRAINT "Appointment_Assignment_History_New_Psychologist_fk" FOREIGN KEY (new_psy_id)
        REFERENCES public.psychologist (psy_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Appointment_Assignment_History_Secretary_fk" FOREIGN KEY (sec_id)
        REFERENCES public.users (use_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

COMMENT ON TABLE public.appointment_assignment_history
    IS E'Historial de cambios de asignación de psicólogos a citas para seguimiento y auditoría';
COMMENT ON COLUMN public.appointment_assignment_history.aah_id
    IS E'Identificador del registro de historial';
COMMENT ON COLUMN public.appointment_assignment_history.app_id
    IS E'Identificador de la cita';
COMMENT ON COLUMN public.appointment_assignment_history.old_psy_id
    IS E'Identificador del psicólogo anterior (null si es primera asignación)';
COMMENT ON COLUMN public.appointment_assignment_history.new_psy_id
    IS E'Identificador del nuevo psicólogo asignado';
COMMENT ON COLUMN public.appointment_assignment_history.sec_id
    IS E'Identificador del secretario que realizó el cambio';
COMMENT ON COLUMN public.appointment_assignment_history.aah_changed_at
    IS E'Fecha y hora del cambio de asignación';
COMMENT ON COLUMN public.appointment_assignment_history.aah_reason
    IS E'Motivo del cambio de asignación (opcional)';

CREATE INDEX IF NOT EXISTS "Appointment_Assignment_History_appointment_idx"
    ON public.appointment_assignment_history (app_id);
CREATE INDEX IF NOT EXISTS "Appointment_Assignment_History_psychologist_idx"
    ON public.appointment_assignment_history (new_psy_id);
CREATE INDEX IF NOT EXISTS "Appointment_Assignment_History_changed_at_idx"
    ON public.appointment_assignment_history (aah_changed_at);

-------------------------------------------------------------------
-- MIGRACIÓN: Normalización de términos y condiciones (policy_documents +
-- policy_acceptance) y mejora de auditoría en clinical_notes_audit
-------------------------------------------------------------------

-- ========================= 1. POLICY DOCUMENTS =========================
-- Contenido versionado e inmutable de cada politica. Cada version nueva
-- es una fila nueva; nunca se sobreescribe una version existente.

CREATE TABLE IF NOT EXISTS public.policy_documents (
    pd_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pd_type varchar(30) NOT NULL,
    pd_version varchar(50) NOT NULL,
    pd_content text NOT NULL,
    pd_effective_from timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Policy_Documents_pk" PRIMARY KEY (pd_id),
    CONSTRAINT "Policy_Documents_type_version_uq" UNIQUE (pd_type, pd_version)
);

COMMENT ON TABLE public.policy_documents
    IS E'Contenido versionado e inmutable de cada politica de terminos y condiciones. Cada version nueva es una fila nueva, nunca se sobreescribe una version existente';
COMMENT ON COLUMN public.policy_documents.pd_id
    IS E'Index, identificador del documento de politica (incrementa automaticamente)';
COMMENT ON COLUMN public.policy_documents.pd_type
    IS E'Tipo de politica: data_treatment, dependent_consent, schedule_terms, clinical_note_terms, entre otros';
COMMENT ON COLUMN public.policy_documents.pd_version
    IS E'Version de la politica dentro de su tipo (ej. v1.0, v1.1)';
COMMENT ON COLUMN public.policy_documents.pd_content
    IS E'Texto completo de la politica en la version indicada';
COMMENT ON COLUMN public.policy_documents.pd_effective_from
    IS E'Fecha y hora desde la cual esta version es la vigente';
COMMENT ON CONSTRAINT "Policy_Documents_pk" ON public.policy_documents
    IS E'Restriccion de identificador unico del documento de politica';
COMMENT ON CONSTRAINT "Policy_Documents_type_version_uq" ON public.policy_documents
    IS E'Impide repetir el mismo numero de version dentro de un mismo tipo de politica';

CREATE INDEX IF NOT EXISTS "Policy_Documents_type_effective_idx"
    ON public.policy_documents (pd_type, pd_effective_from DESC);

COMMENT ON INDEX public."Policy_Documents_type_effective_idx"
    IS E'Optimiza la consulta de la version vigente (mas reciente) por tipo de politica';


-- ========================= 2. POLICY ACCEPTANCE =========================
-- Registra cada evento de aceptacion. El actor siempre es una persona
-- (per_id); dep_id/cn_id son contexto opcional cuando la aceptacion es en
-- nombre de un dependiente o esta asociada a una nota clinica puntual.

CREATE TABLE IF NOT EXISTS public.policy_acceptance (
    pa_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    per_id integer NOT NULL,
    dep_id integer,
    cn_id integer,
    pd_id integer NOT NULL,
    pa_accepted_at timestamptz NOT NULL DEFAULT now(),
    pa_ip_address varchar(50),
    CONSTRAINT "Policy_Acceptance_pk" PRIMARY KEY (pa_id),
    CONSTRAINT "Policy_Acceptance_Person_fk" FOREIGN KEY (per_id)
        REFERENCES public.person (per_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Policy_Acceptance_Dependent_fk" FOREIGN KEY (dep_id)
        REFERENCES public.dependents (dep_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Policy_Acceptance_Clinical_Note_fk" FOREIGN KEY (cn_id)
        REFERENCES public.clinical_notes (cn_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Policy_Acceptance_Document_fk" FOREIGN KEY (pd_id)
        REFERENCES public.policy_documents (pd_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

COMMENT ON TABLE public.policy_acceptance
    IS E'Registro de cada aceptacion de politica. El actor siempre es una persona (per_id); dep_id y cn_id son contexto opcional segun el caso';
COMMENT ON COLUMN public.policy_acceptance.pa_id
    IS E'Index, identificador del registro de aceptacion (incrementa automaticamente)';
COMMENT ON COLUMN public.policy_acceptance.per_id
    IS E'Identificador de la persona que acepta (siempre presente, incluso cuando la aceptacion es en nombre de un dependiente)';
COMMENT ON COLUMN public.policy_acceptance.dep_id
    IS E'Identificador del dependiente, si la aceptacion fue realizada por su tutor en nombre de este';
COMMENT ON COLUMN public.policy_acceptance.cn_id
    IS E'Identificador de la nota clinica, si la aceptacion esta asociada a una nota puntual';
COMMENT ON COLUMN public.policy_acceptance.pd_id
    IS E'Identificador del documento de politica (tipo + version) que fue aceptado';
COMMENT ON COLUMN public.policy_acceptance.pa_accepted_at
    IS E'Fecha y hora en la que se registro la aceptacion';
COMMENT ON COLUMN public.policy_acceptance.pa_ip_address
    IS E'Direccion IP desde la cual se realizo la aceptacion';
COMMENT ON CONSTRAINT "Policy_Acceptance_pk" ON public.policy_acceptance
    IS E'Restriccion de identificador unico del registro de aceptacion';
COMMENT ON CONSTRAINT "Policy_Acceptance_Person_fk" ON public.policy_acceptance
    IS E'Identificador proveniente de persona (quien acepta)';
COMMENT ON CONSTRAINT "Policy_Acceptance_Dependent_fk" ON public.policy_acceptance
    IS E'Identificador proveniente de dependiente, si aplica';
COMMENT ON CONSTRAINT "Policy_Acceptance_Clinical_Note_fk" ON public.policy_acceptance
    IS E'Identificador proveniente de nota clinica, si aplica';
COMMENT ON CONSTRAINT "Policy_Acceptance_Document_fk" ON public.policy_acceptance
    IS E'Identificador proveniente del documento de politica aceptado';

CREATE INDEX IF NOT EXISTS "Policy_Acceptance_person_idx"
    ON public.policy_acceptance (per_id, pd_id);

COMMENT ON INDEX public."Policy_Acceptance_person_idx"
    IS E'Optimiza la consulta del estado de aceptacion vigente por persona y documento de politica';


-- ========================= 3. LIMPIEZA DE COLUMNAS DUPLICADAS =========================
-- Se elimina el patron boolean + timestamp + version repetido en person,
-- dependents, psychologist y clinical_notes, ahora cubierto por
-- policy_acceptance + policy_documents.

ALTER TABLE public.person
    DROP COLUMN IF EXISTS per_termns_accpted,
    DROP COLUMN IF EXISTS per_policy_accepted_at,
    DROP COLUMN IF EXISTS per_policy_version;

ALTER TABLE public.dependents
    DROP COLUMN IF EXISTS dep_termns_accpted,
    DROP COLUMN IF EXISTS dep_policy_accepted_at,
    DROP COLUMN IF EXISTS dep_policy_version;

ALTER TABLE public.psychologist
    DROP COLUMN IF EXISTS psy_termns_accpted,
    DROP COLUMN IF EXISTS psy_policy_accepted_at,
    DROP COLUMN IF EXISTS psy_policy_version;

ALTER TABLE public.clinical_notes
    DROP COLUMN IF EXISTS cn_termns_accpted;


-- ========================= 4. CLINICAL_NOTES_AUDIT =========================
-- Agrega tipo de evento (create/view) para que el log sea interpretable,
-- y DEFAULT now() en cna_date, consistente con el resto del schema.
-- NOTA: las filas ya existentes quedaran marcadas como 'view' por el
-- DEFAULT; si se necesita distinguir cuales correspondian a la creacion
-- original de la nota, revisar/actualizar esas filas manualmente antes
-- de confiar en el reporte historico.

ALTER TABLE public.clinical_notes_audit
    ADD COLUMN IF NOT EXISTS cna_action varchar(10) NOT NULL DEFAULT 'view';

ALTER TABLE public.clinical_notes_audit
    DROP CONSTRAINT IF EXISTS "Clinical_Notes_Audit_action_ck";

ALTER TABLE public.clinical_notes_audit
    ADD CONSTRAINT "Clinical_Notes_Audit_action_ck"
    CHECK (cna_action IN ('create', 'view'));

ALTER TABLE public.clinical_notes_audit
    ALTER COLUMN cna_date SET DEFAULT now();

COMMENT ON COLUMN public.clinical_notes_audit.cna_action
    IS E'Tipo de evento registrado: create (creacion de la nota) o view (consulta/lectura posterior)';
COMMENT ON CONSTRAINT "Clinical_Notes_Audit_action_ck" ON public.clinical_notes_audit
    IS E'Restringe cna_action a los valores conocidos: create o view';


-- ========================= 5. UNICIDAD DE ACEPTACIÓN "PROPIA" POR VERSIÓN =========================
-- Las aceptaciones sin dep_id ni cn_id (politica de tratamiento de datos de
-- una persona, y permisos de trazabilidad y uso de agenda de un psicologo)
-- solo deben poder aceptarse una vez por version de politica. Los casos con
-- dep_id (tutor aceptando en nombre de un dependiente) si pueden repetirse
-- legitimamente, uno por cada dependiente, por lo que la restriccion es
-- parcial y no les aplica.

CREATE UNIQUE INDEX IF NOT EXISTS "Policy_Acceptance_own_version_uq"
    ON public.policy_acceptance (per_id, pd_id)
    WHERE dep_id IS NULL AND cn_id IS NULL;

COMMENT ON INDEX public."Policy_Acceptance_own_version_uq"
    IS E'Impide que una persona -incluido un psicologo aceptando los permisos de trazabilidad y uso de su agenda- acepte mas de una vez la misma version de una politica que no esta asociada a un dependiente ni a una nota clinica';


-- ========================= 6. CONTEXTO DE SOLICITUD (APP_ID) EN POLICY_ACCEPTANCE =========================
-- La aceptacion realizada en el formulario se conserva ligada a cada
-- solicitud (app_id), incluso cuando el consultante reclame despues su
-- cuenta Auth0. Asi queda la evidencia del consentimiento para cada cita
-- propia o de un dependiente. Los consentimientos generales de cuenta
-- permanecen asociados a la persona y los permisos de agenda del psicologo
-- se aceptan una vez por version.

-------------------------------------------------------------------
-- MIGRACIÓN: nueva semántica de disponibilidad/ocupación de agenda
-- schedule representa disponibilidad grande del psicólogo.
-- schedule_occupancy representa intervalos concretos ocupados por citas
-- o bloqueos manuales, y corta la disponibilidad general para cálculos
-- futuros de disponibilidad del frontend.
-------------------------------------------------------------------

-- 1) Se elimina la relación de ocupación directa desde la disponibilidad
--    puntual, porque la agenda del psicólogo ya no representa "ocupado" sino
--    "disponible". Las ocupaciones reales se registran en schedule_occupancy.
ALTER TABLE public.schedule
    DROP CONSTRAINT IF EXISTS "Schedule_Appointment_fk";

ALTER TABLE public.schedule
    DROP COLUMN IF EXISTS app_id;

COMMENT ON TABLE public.schedule
    IS E'Representa los bloques grandes de disponibilidad del psicologo; la ocupacion efectiva se calcula restando los intervalos registrados en schedule_occupancy';
COMMENT ON COLUMN public.schedule.sch_reason
    IS E'Motivo o metadata del bloque de disponibilidad del psicologo; no indica ocupacion ni estado, sino el contexto del intervalo disponible';

-- 2) Nueva tabla de ocupación concreta.
--    Cada fila es un bloqueo real de tiempo que hace que ese rango deje de ser
--    disponible para el psicologo. La cita sigue siendo la fuente principal de
--    ocupación y se referencia por app_id.
CREATE TABLE IF NOT EXISTS public.schedule_occupancy (
    occ_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    psy_id integer NOT NULL,
    app_id integer,
    occ_date date NOT NULL,
    occ_start_time time NOT NULL,
    occ_end_time time NOT NULL,
    source_type varchar(20) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "ScheduleOccupancy_pk" PRIMARY KEY (occ_id),
    CONSTRAINT "ScheduleOccupancy_time_ck" CHECK (occ_end_time > occ_start_time),
    CONSTRAINT "ScheduleOccupancy_source_ck" CHECK (source_type IN ('appointment', 'manual')),
    CONSTRAINT "ScheduleOccupancy_app_unique" UNIQUE (app_id)
);

COMMENT ON TABLE public.schedule_occupancy
    IS E'Intervalos concretos de ocupacion del psicologo. Cada fila representa un rango de tiempo no disponible, generado por una cita asignada o por un bloqueo manual del psicologo';
COMMENT ON COLUMN public.schedule_occupancy.occ_id
    IS E'Identificador del bloqueo de ocupacion';
COMMENT ON COLUMN public.schedule_occupancy.psy_id
    IS E'Identificador del psicologo al que pertenece el intervalo ocupado';
COMMENT ON COLUMN public.schedule_occupancy.app_id
    IS E'Identificador de la cita si el bloqueo proviene de una cita; null si la ocupacion es manual';
COMMENT ON COLUMN public.schedule_occupancy.occ_date
    IS E'Fecha del rango ocupado';
COMMENT ON COLUMN public.schedule_occupancy.occ_start_time
    IS E'Hora de inicio del bloqueo ocupado';
COMMENT ON COLUMN public.schedule_occupancy.occ_end_time
    IS E'Hora final del bloqueo ocupado';
COMMENT ON COLUMN public.schedule_occupancy.source_type
    IS E'Origen del bloqueo: appointment (cita) o manual (bloqueo hecho por el psicologo o secretaria)';
COMMENT ON COLUMN public.schedule_occupancy.created_at
    IS E'Fecha y hora de creacion del bloqueo de ocupacion';
COMMENT ON CONSTRAINT "ScheduleOccupancy_pk" ON public.schedule_occupancy
    IS E'Restriccion de identificador unico del bloqueo ocupado';
COMMENT ON CONSTRAINT "ScheduleOccupancy_time_ck" ON public.schedule_occupancy
    IS E'El fin del bloqueo debe ser posterior al inicio';
COMMENT ON CONSTRAINT "ScheduleOccupancy_source_ck" ON public.schedule_occupancy
    IS E'Los bloqueos ocupados solo pueden originarse en cita o bloqueo manual';
COMMENT ON CONSTRAINT "ScheduleOccupancy_app_unique" ON public.schedule_occupancy
    IS E'Una cita no puede crear mas de un bloqueo de ocupacion';

-- 3) Foreign keys para mantener la integridad del modelo.
ALTER TABLE public.schedule_occupancy
    ADD CONSTRAINT "ScheduleOccupancy_Psychologist_fk"
    FOREIGN KEY (psy_id)
    REFERENCES public.psychologist (psy_id)
    MATCH SIMPLE
    ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE public.schedule_occupancy
    ADD CONSTRAINT "ScheduleOccupancy_Appointment_fk"
    FOREIGN KEY (app_id)
    REFERENCES public.appointments (app_id)
    MATCH SIMPLE
    ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMENT ON CONSTRAINT "ScheduleOccupancy_Psychologist_fk" ON public.schedule_occupancy
    IS E'Identificador proveniente del psicologo propietario del bloqueo';
COMMENT ON CONSTRAINT "ScheduleOccupancy_Appointment_fk" ON public.schedule_occupancy
    IS E'Identificador proveniente de la cita que genero la ocupacion';

-- 4) Indices para consultas frecuentes del frontend y validacion de conflictos.
CREATE INDEX IF NOT EXISTS "Schedule_Occupancy_psychologist_date_idx"
    ON public.schedule_occupancy (psy_id, occ_date, occ_start_time);

CREATE INDEX IF NOT EXISTS "Schedule_Occupancy_app_idx"
    ON public.schedule_occupancy (app_id);

-- Limpia ocupaciones históricas de citas canceladas o descartadas. En adelante,
-- ambas transiciones liberan su ocupación dentro de la misma transacción.
DELETE FROM public.schedule_occupancy occupancy
USING public.appointments appointment
WHERE occupancy.app_id = appointment.app_id
    AND appointment.app_state IN ('cancelada', 'descartada');

COMMENT ON INDEX public."Schedule_Occupancy_psychologist_date_idx"
    IS E'Optimiza la validacion de disponibilidad por psicologo y fecha';
COMMENT ON INDEX public."Schedule_Occupancy_app_idx"
    IS E'Optimiza la consulta del bloqueo de ocupacion asociado a una cita';

-- 5) Nota operativa: schedule sigue siendo la entidad de disponibilidad grande,
--    y se resta la interseccion con schedule_occupancy para calcular la
--    disponibilidad real para frontend y asignacion de citas.

ALTER TABLE public.policy_acceptance
    ADD COLUMN IF NOT EXISTS app_id integer;

ALTER TABLE public.policy_acceptance
    DROP CONSTRAINT IF EXISTS "Policy_Acceptance_Appointment_fk";

ALTER TABLE public.policy_acceptance
    ADD CONSTRAINT "Policy_Acceptance_Appointment_fk" FOREIGN KEY (app_id)
        REFERENCES public.appointments (app_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMENT ON COLUMN public.policy_acceptance.app_id
    IS E'Identificador de la solicitud de cita a la que corresponde esta aceptacion. Cada solicitud (para si mismo o para un dependiente) exige una nueva aceptacion de los terminos vigentes en ese momento, independientemente de que el consultante tenga una cuenta Auth0';
COMMENT ON CONSTRAINT "Policy_Acceptance_Appointment_fk" ON public.policy_acceptance
    IS E'Identificador proveniente de la cita/solicitud que origino la aceptacion, cuando aplica';

-- Se reemplaza el indice de la seccion 5: la unicidad "una sola vez por
-- version" ahora solo aplica cuando la aceptacion tampoco esta atada a una
-- solicitud de cita (app_id IS NULL) -es decir, el caso del psicologo-.
-- Las aceptaciones del consultante, al llevar siempre un app_id, quedan
-- fuera de esta restriccion y pueden repetirse en cada solicitud.

DROP INDEX IF EXISTS "Policy_Acceptance_own_version_uq";

CREATE UNIQUE INDEX IF NOT EXISTS "Policy_Acceptance_own_version_uq"
    ON public.policy_acceptance (per_id, pd_id)
    WHERE dep_id IS NULL AND cn_id IS NULL AND app_id IS NULL;

COMMENT ON INDEX public."Policy_Acceptance_own_version_uq"
    IS E'Impide que una persona sin solicitud de cita asociada -en la practica, el psicologo aceptando los permisos de trazabilidad y uso de su agenda- acepte mas de una vez la misma version de una politica';

-- Evita duplicados por doble clic/reenvio del mismo formulario de
-- solicitud: una misma solicitud no debe generar dos filas de aceptacion
-- para la misma version de politica.

CREATE UNIQUE INDEX IF NOT EXISTS "Policy_Acceptance_request_version_uq"
    ON public.policy_acceptance (app_id, pd_id)
    WHERE app_id IS NOT NULL;

COMMENT ON INDEX public."Policy_Acceptance_request_version_uq"
    IS E'Impide registrar dos veces la aceptacion de la misma version de politica para una misma solicitud de cita (por ejemplo, por doble envio del formulario)';

CREATE INDEX IF NOT EXISTS "Policy_Acceptance_appointment_idx"
    ON public.policy_acceptance (app_id);


-- ========================= 7. UNICIDAD DE ACEPTACIÓN POR NOTA CLÍNICA =========================
-- Cada nota clinica que se crea es su propio evento de aceptacion, igual
-- que cada solicitud de cita: no hay limite de cuantas notas -y por tanto
-- cuantas aceptaciones- puede generar un psicologo en el tiempo. Este
-- indice NO es una restriccion de "una sola vez para siempre" (esa logica
-- es exclusiva de los permisos de agenda del psicologo, seccion 6); solo
-- evita que una misma nota quede con dos filas de aceptacion duplicadas
-- para la misma version de politica, por ejemplo por doble envio del
-- formulario.

CREATE UNIQUE INDEX IF NOT EXISTS "Policy_Acceptance_note_version_uq"
    ON public.policy_acceptance (cn_id, pd_id)
    WHERE cn_id IS NOT NULL;

COMMENT ON INDEX public."Policy_Acceptance_note_version_uq"
    IS E'Evita duplicar la fila de aceptacion de una misma nota clinica para la misma version de politica (doble envio). No limita cuantas notas distintas -cada una con su propia aceptacion- puede crear un psicologo';


-- ========================= 8. MIGRACIÓN: PSYCHOLOGIST FK A PERSON =========================
-- El secretario crea personas con roles (incluyendo psicologo) antes de que
-- el usuario tenga cuenta en users. El constraint Psychologist_User_fk debe
-- referenciar a person.per_id en lugar de users.use_id para permitir este flujo.

ALTER TABLE public.psychologist
    DROP CONSTRAINT IF EXISTS "Psychologist_User_fk" CASCADE;

ALTER TABLE public.psychologist
    ADD CONSTRAINT "Psychologist_User_fk" FOREIGN KEY (psy_id)
        REFERENCES public.person (per_id) MATCH SIMPLE
        ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMENT ON CONSTRAINT "Psychologist_User_fk" ON public.psychologist
    IS E'Identificador proveniente de persona (un psicologo puede existir antes de tener cuenta de usuario)';

-- ========================= MIGRATION 29/09/2026 =========================
-- Columna usada por la entidad Person y por las solicitudes de cita (HE-2).
-- ========================================================================

ALTER TABLE public.person
    ADD COLUMN IF NOT EXISTS per_residence_zone varchar(255);

COMMENT ON COLUMN public.person.per_residence_zone
    IS E'Zona de residencia de la persona registrada en la solicitud de cita';

-- ========================= MIGRATION 28/09/2026 =========================
-- HE-04 Gestion de contenido institucional (administrador y marketing).
-- Solo agrega tablas nuevas; content_items se reutiliza sin cambios.
-- ========================================================================

CREATE TABLE IF NOT EXISTS public.content_cards (
    cc_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cc_section varchar(20) NOT NULL,
    cc_title varchar(150) NOT NULL,
    cc_subtitle varchar(150),
    cc_description text,
    cc_image_url varchar(500),
    cc_image_alt varchar(150),
    cc_order integer NOT NULL DEFAULT 0,
    cc_is_active boolean NOT NULL DEFAULT true,
    cc_updated_by integer NOT NULL,
    cc_updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Content_Cards_pk" PRIMARY KEY (cc_id),
    CONSTRAINT "Content_Cards_section_ck" CHECK (cc_section IN ('values','team','services','programs')),
    CONSTRAINT "Content_Cards_image_alt_ck" CHECK (cc_image_url IS NULL OR cc_image_alt IS NOT NULL),
    CONSTRAINT "Content_Cards_User_fk" FOREIGN KEY (cc_updated_by)
        REFERENCES public.users (use_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

COMMENT ON TABLE public.content_cards
    IS E'Elementos en lista del contenido institucional: valores, equipo, servicios y programas';
COMMENT ON COLUMN public.content_cards.cc_section
    IS E'Seccion a la que pertenece: values, team, services o programs';
COMMENT ON COLUMN public.content_cards.cc_title
    IS E'Titulo del elemento; en team es el nombre de la persona';
COMMENT ON COLUMN public.content_cards.cc_subtitle
    IS E'Texto secundario; en team es el cargo';
COMMENT ON COLUMN public.content_cards.cc_image_url
    IS E'URL de la imagen en Cloudinary. No se almacena el binario en la BD';
COMMENT ON COLUMN public.content_cards.cc_order
    IS E'Posicion del elemento dentro de su seccion';
COMMENT ON COLUMN public.content_cards.cc_is_active
    IS E'Indica si el elemento se muestra en el sitio publico';
COMMENT ON COLUMN public.content_cards.cc_updated_by
    IS E'Usuario (administrador o marketing) que realizo la ultima modificacion';

CREATE INDEX IF NOT EXISTS "Content_Cards_section_order_idx"
    ON public.content_cards (cc_section, cc_order);

CREATE TABLE IF NOT EXISTS public.news (
    nw_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nw_title varchar(150) NOT NULL,
    nw_body text NOT NULL,
    nw_image_url varchar(500),
    nw_image_alt varchar(150),
    nw_status varchar(10) NOT NULL DEFAULT 'published',
    nw_published_at timestamptz NOT NULL DEFAULT now(),
    nw_is_pinned boolean NOT NULL DEFAULT false,
    nw_created_by integer NOT NULL,
    nw_updated_by integer NOT NULL,
    nw_updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "News_pk" PRIMARY KEY (nw_id),
    CONSTRAINT "News_status_ck" CHECK (nw_status IN ('published','retired')),
    CONSTRAINT "News_pinned_published_ck" CHECK (NOT nw_is_pinned OR nw_status = 'published'),
    CONSTRAINT "News_image_alt_ck" CHECK (nw_image_url IS NULL OR nw_image_alt IS NOT NULL),
    CONSTRAINT "News_Created_By_fk" FOREIGN KEY (nw_created_by)
        REFERENCES public.users (use_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "News_Updated_By_fk" FOREIGN KEY (nw_updated_by)
        REFERENCES public.users (use_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

COMMENT ON TABLE public.news
    IS E'Noticias publicadas por administrador o marketing en el sitio publico';
COMMENT ON COLUMN public.news.nw_body
    IS E'Contenido en Markdown limitado: negrita, cursiva y enlaces';
COMMENT ON COLUMN public.news.nw_status
    IS E'published se muestra en el sitio; retired se oculta pero se conserva';
COMMENT ON COLUMN public.news.nw_published_at
    IS E'Fecha de publicacion; se asigna al crear y no se edita';
COMMENT ON COLUMN public.news.nw_is_pinned
    IS E'Noticia fijada: se muestra primera. Solo puede haber una';

CREATE UNIQUE INDEX IF NOT EXISTS "News_single_pinned_uq"
    ON public.news (nw_is_pinned) WHERE nw_is_pinned;
CREATE INDEX IF NOT EXISTS "News_status_published_idx"
    ON public.news (nw_status, nw_published_at DESC);

CREATE TABLE IF NOT EXISTS public.gallery_images (
    gi_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    gi_image_url varchar(500) NOT NULL,
    gi_image_alt varchar(150) NOT NULL,
    gi_caption varchar(200),
    gi_status varchar(10) NOT NULL DEFAULT 'published',
    gi_order integer NOT NULL DEFAULT 0,
    gi_created_by integer NOT NULL,
    gi_updated_by integer NOT NULL,
    gi_updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Gallery_Images_pk" PRIMARY KEY (gi_id),
    CONSTRAINT "Gallery_Images_status_ck" CHECK (gi_status IN ('published','retired')),
    CONSTRAINT "Gallery_Images_Created_By_fk" FOREIGN KEY (gi_created_by)
        REFERENCES public.users (use_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Gallery_Images_Updated_By_fk" FOREIGN KEY (gi_updated_by)
        REFERENCES public.users (use_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

COMMENT ON TABLE public.gallery_images
    IS E'Imagenes de la galeria del sitio publico';
COMMENT ON COLUMN public.gallery_images.gi_status
    IS E'published se muestra en el sitio; retired se oculta pero se conserva';
COMMENT ON COLUMN public.gallery_images.gi_order
    IS E'Posicion de la imagen en la galeria';

CREATE INDEX IF NOT EXISTS "Gallery_Images_status_order_idx"
    ON public.gallery_images (gi_status, gi_order);

CREATE TABLE IF NOT EXISTS public.banners (
    ban_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ban_title varchar(120) NOT NULL,
    ban_image_url varchar(500),
    ban_image_alt varchar(150),
    ban_starts_at timestamptz,
    ban_ends_at timestamptz,
    ban_is_active boolean NOT NULL DEFAULT false,
    ban_created_by integer NOT NULL,
    ban_updated_by integer NOT NULL,
    ban_updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Banners_pk" PRIMARY KEY (ban_id),
    CONSTRAINT "Banners_period_ck" CHECK (ban_starts_at IS NULL OR ban_ends_at IS NULL OR ban_ends_at > ban_starts_at),
    CONSTRAINT "Banners_active_requires_ck" CHECK (
        NOT ban_is_active
        OR (ban_image_url IS NOT NULL AND ban_starts_at IS NOT NULL AND ban_ends_at IS NOT NULL)
    ),
    CONSTRAINT "Banners_image_alt_ck" CHECK (ban_image_url IS NULL OR ban_image_alt IS NOT NULL),
    CONSTRAINT "Banners_Created_By_fk" FOREIGN KEY (ban_created_by)
        REFERENCES public.users (use_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT "Banners_Updated_By_fk" FOREIGN KEY (ban_updated_by)
        REFERENCES public.users (use_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

COMMENT ON TABLE public.banners
    IS E'Banners de la pagina de inicio con periodo de vigencia';
COMMENT ON COLUMN public.banners.ban_starts_at
    IS E'Inicio de la vigencia; el banner no se muestra antes de esta fecha';
COMMENT ON COLUMN public.banners.ban_ends_at
    IS E'Fin de la vigencia; despues de esta fecha deja de mostrarse sin intervencion manual';
COMMENT ON COLUMN public.banners.ban_is_active
    IS E'Activado por el usuario. Requiere imagen y vigencia completa';

CREATE INDEX IF NOT EXISTS "Banners_active_ends_idx"
    ON public.banners (ban_is_active, ban_ends_at);

CREATE TABLE IF NOT EXISTS public.content_change_log (
    ccl_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    use_id integer NOT NULL,
    ccl_content_type varchar(20) NOT NULL,
    ccl_content_id integer NOT NULL,
    ccl_action varchar(15) NOT NULL,
    ccl_changed_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "Content_Change_Log_pk" PRIMARY KEY (ccl_id),
    CONSTRAINT "Content_Change_Log_type_ck" CHECK (
        ccl_content_type IN ('content_item','content_card','news','gallery_image','banner')
    ),
    CONSTRAINT "Content_Change_Log_action_ck" CHECK (
        ccl_action IN ('create','update','delete','publish','retire','activate','deactivate','pin','unpin')
    ),
    CONSTRAINT "Content_Change_Log_User_fk" FOREIGN KEY (use_id)
        REFERENCES public.users (use_id)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

COMMENT ON TABLE public.content_change_log
    IS E'Tabla intermedia usuarios - contenido: registra quien modifico cada contenido y cuando';
COMMENT ON COLUMN public.content_change_log.use_id
    IS E'Usuario que realizo el cambio';
COMMENT ON COLUMN public.content_change_log.ccl_content_type
    IS E'Tabla del contenido modificado: content_item, content_card, news, gallery_image o banner';
COMMENT ON COLUMN public.content_change_log.ccl_content_id
    IS E'Identificador del registro modificado dentro de su tabla';
COMMENT ON COLUMN public.content_change_log.ccl_action
    IS E'Accion realizada sobre el contenido';

CREATE INDEX IF NOT EXISTS "Content_Change_Log_content_idx"
    ON public.content_change_log (ccl_content_type, ccl_content_id, ccl_changed_at DESC);
CREATE INDEX IF NOT EXISTS "Content_Change_Log_user_idx"
    ON public.content_change_log (use_id);

ALTER TABLE public.appointments
    DROP COLUMN IF EXISTS app_date_ideal;

-- Cola durable de correo SMTP. Aplicable sobre bases existentes.
-- El contenido del mensaje se elimina al marcarse como enviado.

CREATE TABLE IF NOT EXISTS public.email_outbox (
    email_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email_to varchar(320),
    email_subject varchar(998),
    email_text text,
    email_html text,
    email_status varchar(10) NOT NULL DEFAULT 'pending',
    email_attempts integer NOT NULL DEFAULT 0,
    email_next_attempt_at timestamptz NOT NULL DEFAULT now(),
    email_locked_at timestamptz,
    email_last_error_code varchar(80),
    email_created_at timestamptz NOT NULL DEFAULT now(),
    email_sent_at timestamptz,
    CONSTRAINT "Email_Outbox_pk" PRIMARY KEY (email_id),
    CONSTRAINT "Email_Outbox_status_ck" CHECK (email_status IN ('pending', 'sending', 'sent')),
    CONSTRAINT "Email_Outbox_attempts_ck" CHECK (email_attempts >= 0),
    CONSTRAINT "Email_Outbox_payload_ck" CHECK (
        (email_status = 'sent' AND email_to IS NULL AND email_subject IS NULL
            AND email_text IS NULL AND email_html IS NULL)
        OR
        (email_status <> 'sent' AND email_to IS NOT NULL AND email_subject IS NOT NULL
            AND email_text IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS "Email_Outbox_pending_idx"
    ON public.email_outbox (email_status, email_next_attempt_at, email_created_at);
CREATE INDEX IF NOT EXISTS "Email_Outbox_stale_lock_idx"
    ON public.email_outbox (email_locked_at)
    WHERE email_status = 'sending';
-- ========================= MIGRATION 06/10/2026 =========================
-- Los banners dejan de tener vigencia: se muestran mientras esten activos.
-- ========================================================================

ALTER TABLE public.banners
    DROP CONSTRAINT IF EXISTS "Banners_period_ck",
    DROP CONSTRAINT IF EXISTS "Banners_active_requires_ck";

DROP INDEX IF EXISTS public."Banners_active_ends_idx";

ALTER TABLE public.banners
    DROP COLUMN IF EXISTS ban_starts_at,
    DROP COLUMN IF EXISTS ban_ends_at;

ALTER TABLE public.banners
    ADD CONSTRAINT "Banners_active_requires_ck" CHECK (NOT ban_is_active OR ban_image_url IS NOT NULL);

COMMENT ON TABLE public.banners
    IS E'Banners de la pagina de inicio; los activos rotan en la primera pantalla';
COMMENT ON COLUMN public.banners.ban_is_active
    IS E'Activado por el usuario. Requiere imagen';
